import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Button,
  Card,
  Checkbox,
  Form,
  Input,
  Modal,
  Popconfirm,
  Select,
  Space,
  Table,
  Tag,
  Typography,
} from "antd";
import { useList, useInvalidate } from "@refinedev/core";
import { APIError } from "./api";
import { localeSelectOptions } from "./locales";
import type { AdminLocale } from "./locales";
import { dataProvider } from "./dataProvider";
import { catalogCommands } from "./catalogCommands";
import { useAdminIdentity } from "./AdminProviders";
import { ProductDataModal } from "./ProductDataModal";
import { ProductTranslationsModal } from "./ProductTranslationsModal";
import type {
  Category,
  DictionaryEntry,
  Product,
  ProductForm,
  SiteSettings,
} from "./types";

type Feedback = {
  onError: (error: unknown) => void;
  onMessage: (message: string) => void;
};
type CatalogLocale = AdminLocale;

const urlSaveUnconfirmedText: Record<AdminLocale, string> = {
  "en-US": "URL save was not confirmed:",
  "zh-TW": "URL 尚未確認保存：",
  "zh-CN": "URL 保存尚未确认：",
  "ja-JP": "URL の保存を確認できませんでした：",
  "ko-KR": "URL 저장이 확인되지 않았습니다:",
  "de-DE": "Das Speichern der URL wurde nicht bestätigt:",
  "fr-FR": "L’enregistrement de l’URL n’a pas été confirmé :",
  "it-IT": "Il salvataggio dell’URL non è stato confermato:",
  "es-ES": "No se confirmó el guardado de la URL:",
  "pt-BR": "O salvamento da URL não foi confirmado:",
};

const labels = {
  "en-US": {
    cloned: (source: string, created: string) =>
      `Cloned ${source} as ${created}. The clone is Hidden.`,
    saved: (part: string, revision: number) =>
      `Saved ${part} revision ${revision}.`,
    created: (part: string) => `Created ${part} as Hidden.`,
    mutated: (part: string, action: string) =>
      `${part} ${action === "hide" ? "hidden" : "archived"}.`,
    published: (part: string, revision: number) =>
      `${part} publication was queued at revision ${revision}.`,
    exportDownloaded: "Product export downloaded.",
    products: "Products",
    includeArchived: "Include archived",
    export: "Export XLSX",
    refresh: "Refresh",
    newProduct: "New product",
    partNumber: "Part number",
    name: "Name",
    manufacturer: "Manufacturer",
    category: "Category",
    state: "State",
    actions: "Actions",
    edit: "Edit",
    data: "Data",
    translations: "Translations",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Defaults from the current Website Site Default, not your Admin UI language. You may override it for this Product.",
    clone: "Clone",
    publishConfirm: "Publish this product?",
    publishDescription:
      "The complete Product publication unit will become public after activation.",
    publish: "Publish",
    hideConfirm: "Hide this product from new public requests?",
    hide: "Hide",
    archiveConfirm: "Archive this product? Archived records are read-only.",
    archive: "Archive",
    editTitle: (part: string) => `Edit ${part}`,
    cloneTitle: (part: string) => `Clone ${part}`,
    save: "Save",
    createClone: "Create Hidden clone",
    createHidden: "Create Hidden product",
    publicTitle: "This Product is currently public",
    publicDescription:
      "Saving creates a new public revision. The current revision remains available until the complete replacement publication unit activates.",
    cloneInfo: "Create an independent Hidden clone",
    cloneDescription:
      "Enter a new Part Number. Product data and valid asset, image, document, specification, and application references are copied from the source.",
    slug: "URL slug",
    slugEdit: "Changing this changes the public URL.",
    slugCreate: "Leave blank to generate a stable suggestion once.",
    autoGenerated: "auto-generated",
    customPath: "Custom public path",
    customPathHelp:
      "Optional full internal path; it stays fixed when the global pattern changes.",
    customPathPlaceholder: "/featured/example",
    productName: "Product name",
    brand: "Brand",
    applications: "Applications",
    lifecycle: "Lifecycle",
    package: "Package / form factor",
    visibility: "Visibility",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Legacy document URL",
    description: "Description",
    features: "Features",
    specification: "Specification",
    preview: "Preview unsaved changes",
    current: "current",
    archivedStatus: "archived",
  },
  "zh-TW": {
    cloned: (source: string, created: string) =>
      `已將 ${source} 複製為 ${created}；副本為 Hidden。`,
    saved: (part: string, revision: number) =>
      `已儲存 ${part} 修訂 ${revision}。`,
    created: (part: string) => `已建立 ${part}，狀態為 Hidden。`,
    mutated: (part: string, action: string) =>
      `${part} 已${action === "hide" ? "隱藏" : "封存"}。`,
    published: (part: string, revision: number) =>
      `${part} 的修訂 ${revision} 已排入發布。`,
    exportDownloaded: "產品匯出檔已下載。",
    products: "產品",
    includeArchived: "包含已封存",
    export: "匯出 XLSX",
    refresh: "重新整理",
    newProduct: "新增產品",
    partNumber: "料號",
    name: "名稱",
    manufacturer: "Manufacturer",
    category: "分類",
    state: "狀態",
    actions: "操作",
    edit: "編輯",
    data: "資料",
    translations: "翻譯",
    sourceLocale: "來源語系",
    sourceLocaleHelp: "預設取目前 Website Site Default，而不是你的 Admin UI 語系；此 Product 可單獨改選。",
    clone: "複製",
    publishConfirm: "要發布這項產品嗎？",
    publishDescription: "完整的 Product publication unit 啟用後才會公開。",
    publish: "發布",
    hideConfirm: "要停止核准這項產品的新公開請求嗎？",
    hide: "隱藏",
    archiveConfirm: "要封存這項產品嗎？封存後資料為唯讀。",
    archive: "封存",
    editTitle: (part: string) => `編輯 ${part}`,
    cloneTitle: (part: string) => `複製 ${part}`,
    save: "儲存",
    createClone: "建立 Hidden 副本",
    createHidden: "建立 Hidden 產品",
    publicTitle: "這項產品目前已公開",
    publicDescription:
      "儲存會建立新的公開修訂；目前修訂會保持可用，直到完整替代 publication unit 啟用。",
    cloneInfo: "建立獨立的 Hidden 副本",
    cloneDescription:
      "請輸入新料號。產品資料及有效的資產、圖片、文件、規格與應用參照會從來源複製。",
    slug: "URL slug",
    slugEdit: "變更後公開 URL 也會改變。",
    slugCreate: "留空時只會產生一次穩定建議。",
    autoGenerated: "自動產生",
    customPath: "自訂公開路徑",
    customPathHelp: "選填的完整內部路徑；全站 URL pattern 變更時仍保持固定。",
    customPathPlaceholder: "/featured/example",
    productName: "產品名稱",
    brand: "品牌",
    applications: "應用",
    lifecycle: "生命週期",
    package: "封裝／外型",
    visibility: "可見性",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "舊式文件 URL",
    description: "描述",
    features: "特色",
    specification: "規格",
    preview: "預覽未儲存變更",
    current: "目前",
    archivedStatus: "已封存",
  },
"zh-CN": {
    cloned: (source: string, created: string) => `\u514B\u9686${source}\u4F5C\u4E3A${created}\u3002\u514B\u9686\u4F53\u662FHidden\u3002`,
    saved: (part: string, revision: number) => `\u5DF2\u4FDD\u5B58${part}\u4FEE\u8BA2${revision}.`,
    created: (part: string) => `\u5DF2\u521B\u5EFA${part}\u5982Hidden\u3002`,
    mutated: (part: string, action: string) => `${part} ${action === "\u9690\u85CF" ? "\u9690" : "\u5DF2\u5F52\u6863"}.`,
    published: (part: string, revision: number) => `${part}\u51FA\u7248\u7269\u5728\u4FEE\u8BA2\u65F6\u6392\u961F${revision}.`,
    exportDownloaded: "Product \u5BFC\u51FA\u5DF2\u4E0B\u8F7D\u3002",
    products: "\u4EA7\u54C1",
    includeArchived: "\u5305\u62EC\u5B58\u6863\u7684",
    export: "\u51FA\u53E3XLSX",
    refresh: "\u5237\u65B0",
    newProduct: "\u65B0\u4EA7\u54C1",
    partNumber: "\u96F6\u4EF6\u7F16\u53F7",
    name: "\u59D3\u540D",
    manufacturer: "\u5236\u9020\u5546",
    category: "\u7C7B\u522B",
    state: "\u72B6\u6001",
    actions: "\u884C\u52A8",
    edit: "\u7F16\u8F91",
    data: "\u6570\u636E",
    translations: "\u7FFB\u8BD1",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "\u9ED8\u8BA4\u4E3A\u5F53\u524D Website Site Default\uFF0C\u800C\u4E0D\u662F\u60A8\u7684 Admin UI \u8BED\u8A00\u3002\u60A8\u53EF\u4EE5\u4E3A\u6B64 Product \u8986\u76D6\u5B83\u3002",
    clone: "\u514B\u9686",
    publishConfirm: "Publish \u8FD9\u4E2A\u4EA7\u54C1\uFF1F",
    publishDescription: "\u5B8C\u6574\u7684Product\u53D1\u5E03\u5355\u5143\u5728\u6FC0\u6D3B\u540E\u5C06\u516C\u5F00\u3002",
    publish: "Publish",
    hideConfirm: "\u9690\u85CF\u8BE5\u4EA7\u54C1\u4EE5\u5E94\u5BF9\u65B0\u7684\u516C\u4F17\u8BF7\u6C42\uFF1F",
    hide: "\u9690\u85CF",
    archiveConfirm: "\u5B58\u6863\u6B64\u4EA7\u54C1\uFF1F Archived \u8BB0\u5F55\u662F\u53EA\u8BFB\u7684\u3002",
    archive: "\u6863\u6848",
    editTitle: (part: string) => `\u7F16\u8F91${part}`,
    cloneTitle: (part: string) => `\u514B\u9686${part}`,
    save: "\u8282\u7701",
    createClone: "\u521B\u5EFA Hidden \u514B\u9686",
    createHidden: "\u521B\u5EFAHidden\u4EA7\u54C1",
    publicTitle: "\u6B64Product\u76EE\u524D\u5DF2\u516C\u5F00",
    publicDescription: "\u4FDD\u5B58\u4F1A\u521B\u5EFA\u65B0\u7684\u516C\u5171\u4FEE\u8BA2\u3002\u5728\u5B8C\u6574\u7684\u66FF\u6362\u53D1\u5E03\u5355\u5143\u6FC0\u6D3B\u4E4B\u524D\uFF0C\u5F53\u524D\u4FEE\u8BA2\u7248\u4ECD\u7136\u53EF\u7528\u3002",
    cloneInfo: "\u521B\u5EFA\u72EC\u7ACB\u7684Hidden\u514B\u9686",
    cloneDescription: "\u8F93\u5165\u65B0\u7684\u96F6\u4EF6\u53F7\u3002 Product \u6570\u636E\u548C\u6709\u6548\u8D44\u4EA7\u3001\u56FE\u50CF\u3001\u6587\u6863\u3001\u89C4\u8303\u548C\u5E94\u7528\u7A0B\u5E8F\u53C2\u8003\u662F\u4ECE\u6E90\u590D\u5236\u7684\u3002",
    slug: "URL \u86DE\u8753",
    slugEdit: "\u6539\u53D8\u8FD9\u4E2A\u4F1A\u6539\u53D8\u516C\u5171URL\u3002",
    slugCreate: "\u7559\u7A7A\u53EF\u751F\u6210\u4E00\u6B21\u7A33\u5B9A\u7684\u5EFA\u8BAE\u3002",
    autoGenerated: "\u81EA\u52A8\u751F\u6210",
    customPath: "\u81EA\u5B9A\u4E49\u516C\u5171\u8DEF\u5F84",
    customPathHelp: "\u53EF\u9009\u7684\u5B8C\u6574\u5185\u90E8\u8DEF\u5F84\uFF1B\u5F53\u5168\u5C40\u6A21\u5F0F\u53D1\u751F\u53D8\u5316\u65F6\uFF0C\u5B83\u4FDD\u6301\u4E0D\u53D8\u3002",
    customPathPlaceholder: "/\u7CBE\u9009/\u793A\u4F8B",
    productName: "Product \u540D\u79F0",
    brand: "\u54C1\u724C",
    applications: "\u5E94\u7528\u9886\u57DF",
    lifecycle: "\u751F\u547D\u5468\u671F",
    package: "\u5C01\u88C5/\u5916\u5F62\u5C3A\u5BF8",
    visibility: "\u80FD\u89C1\u5EA6",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "\u65E7\u6587\u6863 URL",
    description: "\u63CF\u8FF0",
    features: "\u7279\u5F81",
    specification: "\u89C4\u683C",
    preview: "Preview \u672A\u4FDD\u5B58\u7684\u66F4\u6539",
    current: "\u5F53\u524D\u7684",
    archivedStatus: "\u5DF2\u5F52\u6863",
},
"ja-JP": {
    cloned: (source: string, created: string) => `\u30AF\u30ED\u30FC\u30F3\u5316\u3055\u308C\u305F${source}\u3068\u3057\u3066${created}\u3002\u30AF\u30ED\u30FC\u30F3\u306F Hidden \u3067\u3059\u3002`,
    saved: (part: string, revision: number) => `\u4FDD\u5B58\u3055\u308C\u307E\u3057\u305F${part}\u30EA\u30D3\u30B8\u30E7\u30F3${revision}.`,
    created: (part: string) => `\u4F5C\u6210\u3055\u308C\u307E\u3057\u305F${part}Hidden\u3068\u3057\u3066\u3002`,
    mutated: (part: string, action: string) => `${part} ${action === "\u96A0\u308C\u308B" ? "\u96A0\u308C\u305F" : "\u30A2\u30FC\u30AB\u30A4\u30D6\u3055\u308C\u305F"}.`,
    published: (part: string, revision: number) => `${part}\u30D1\u30D6\u30EA\u30B1\u30FC\u30B7\u30E7\u30F3\u306F\u6539\u8A02\u6642\u306B\u30AD\u30E5\u30FC\u306B\u5165\u308C\u3089\u308C\u307E\u3057\u305F${revision}.`,
    exportDownloaded: "Product \u30A8\u30AF\u30B9\u30DD\u30FC\u30C8\u304C\u30C0\u30A6\u30F3\u30ED\u30FC\u30C9\u3055\u308C\u307E\u3057\u305F\u3002",
    products: "\u88FD\u54C1",
    includeArchived: "\u30A2\u30FC\u30AB\u30A4\u30D6\u3092\u542B\u3081\u308B",
    export: "XLSX\u3092\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8",
    refresh: "\u30EA\u30D5\u30EC\u30C3\u30B7\u30E5",
    newProduct: "\u65B0\u88FD\u54C1",
    partNumber: "\u90E8\u54C1\u756A\u53F7",
    name: "\u540D\u524D",
    manufacturer: "\u30E1\u30FC\u30AB\u30FC",
    category: "\u30AB\u30C6\u30B4\u30EA",
    state: "\u5DDE",
    actions: "\u30A2\u30AF\u30B7\u30E7\u30F3",
    edit: "\u7DE8\u96C6",
    data: "\u30C7\u30FC\u30BF",
    translations: "\u7FFB\u8A33",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Admin UI \u8A00\u8A9E\u3067\u306F\u306A\u304F\u3001\u73FE\u5728\u306E Website Site Default \u304B\u3089\u306E\u30C7\u30D5\u30A9\u30EB\u30C8\u3002\u3053\u306E Product \u3067\u306F\u3053\u308C\u3092\u30AA\u30FC\u30D0\u30FC\u30E9\u30A4\u30C9\u3067\u304D\u307E\u3059\u3002",
    clone: "\u30AF\u30ED\u30FC\u30F3",
    publishConfirm: "Publish\u3053\u306E\u5546\u54C1\u306F\uFF1F",
    publishDescription: "\u5B8C\u5168\u306A Product \u516C\u958B\u30E6\u30CB\u30C3\u30C8\u306F\u3001\u30A2\u30AF\u30C6\u30A3\u30D6\u5316\u5F8C\u306B\u516C\u958B\u3055\u308C\u307E\u3059\u3002",
    publish: "Publish",
    hideConfirm: "\u3053\u306E\u5546\u54C1\u3092\u65B0\u3057\u3044\u516C\u958B\u30EA\u30AF\u30A8\u30B9\u30C8\u304B\u3089\u975E\u8868\u793A\u306B\u3057\u307E\u3059\u304B?",
    hide: "\u96A0\u308C\u308B",
    archiveConfirm: "\u3053\u306E\u88FD\u54C1\u3092\u30A2\u30FC\u30AB\u30A4\u30D6\u3057\u307E\u3059\u304B? Archived \u30EC\u30B3\u30FC\u30C9\u306F\u8AAD\u307F\u53D6\u308A\u5C02\u7528\u3067\u3059\u3002",
    archive: "\u30A2\u30FC\u30AB\u30A4\u30D6",
    editTitle: (part: string) => `\u7DE8\u96C6${part}`,
    cloneTitle: (part: string) => `\u30AF\u30ED\u30FC\u30F3${part}`,
    save: "\u4FDD\u5B58",
    createClone: "Hidden \u30AF\u30ED\u30FC\u30F3\u3092\u4F5C\u6210\u3059\u308B",
    createHidden: "Hidden \u88FD\u54C1\u306E\u4F5C\u6210",
    publicTitle: "\u3053\u306E Product \u306F\u73FE\u5728\u516C\u958B\u3055\u308C\u3066\u3044\u307E\u3059",
    publicDescription: "\u4FDD\u5B58\u3059\u308B\u3068\u3001\u65B0\u3057\u3044\u516C\u958B\u30EA\u30D3\u30B8\u30E7\u30F3\u304C\u4F5C\u6210\u3055\u308C\u307E\u3059\u3002\u73FE\u5728\u306E\u30EA\u30D3\u30B8\u30E7\u30F3\u306F\u3001\u5B8C\u5168\u306B\u7F6E\u304D\u63DB\u3048\u3089\u308C\u308B\u30D1\u30D6\u30EA\u30B1\u30FC\u30B7\u30E7\u30F3 \u30E6\u30CB\u30C3\u30C8\u304C\u30A2\u30AF\u30C6\u30A3\u30D6\u5316\u3055\u308C\u308B\u307E\u3067\u5229\u7528\u53EF\u80FD\u3067\u3059\u3002",
    cloneInfo: "\u72EC\u7ACB\u3057\u305F Hidden \u30AF\u30ED\u30FC\u30F3\u3092\u4F5C\u6210\u3059\u308B",
    cloneDescription: "\u65B0\u3057\u3044\u90E8\u54C1\u756A\u53F7\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002 Product \u30C7\u30FC\u30BF\u3068\u6709\u52B9\u306A\u30A2\u30BB\u30C3\u30C8\u3001\u753B\u50CF\u3001\u30C9\u30AD\u30E5\u30E1\u30F3\u30C8\u3001\u4ED5\u69D8\u3001\u304A\u3088\u3073\u30A2\u30D7\u30EA\u30B1\u30FC\u30B7\u30E7\u30F3\u53C2\u7167\u304C\u30BD\u30FC\u30B9\u304B\u3089\u30B3\u30D4\u30FC\u3055\u308C\u307E\u3059\u3002",
    slug: "URL\u30CA\u30E1\u30AF\u30B8",
    slugEdit: "\u3053\u308C\u3092\u5909\u66F4\u3059\u308B\u3068\u3001\u30D1\u30D6\u30EA\u30C3\u30AF URL \u304C\u5909\u66F4\u3055\u308C\u307E\u3059\u3002",
    slugCreate: "\u5B89\u5B9A\u3057\u305F\u63D0\u6848\u3092\u4E00\u5EA6\u751F\u6210\u3059\u308B\u306B\u306F\u3001\u7A7A\u767D\u306E\u307E\u307E\u306B\u3057\u307E\u3059\u3002",
    autoGenerated: "\u81EA\u52D5\u751F\u6210",
    customPath: "\u30AB\u30B9\u30BF\u30E0\u30D1\u30D6\u30EA\u30C3\u30AF\u30D1\u30B9",
    customPathHelp: "\u30AA\u30D7\u30B7\u30E7\u30F3\u306E\u5B8C\u5168\u306A\u5185\u90E8\u30D1\u30B9\u3002\u30B0\u30ED\u30FC\u30D0\u30EB \u30D1\u30BF\u30FC\u30F3\u304C\u5909\u5316\u3057\u3066\u3082\u3001\u56FA\u5B9A\u3055\u308C\u305F\u307E\u307E\u306B\u306A\u308A\u307E\u3059\u3002",
    customPathPlaceholder: "/\u7279\u96C6/\u4F8B",
    productName: "Product \u540D\u524D",
    brand: "\u30D6\u30E9\u30F3\u30C9",
    applications: "\u30A2\u30D7\u30EA\u30B1\u30FC\u30B7\u30E7\u30F3",
    lifecycle: "\u30E9\u30A4\u30D5\u30B5\u30A4\u30AF\u30EB",
    package: "\u30D1\u30C3\u30B1\u30FC\u30B8/\u30D5\u30A9\u30FC\u30E0\u30D5\u30A1\u30AF\u30BF\u30FC",
    visibility: "\u53EF\u8996\u6027",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "\u30EC\u30AC\u30B7\u30FC\u30C9\u30AD\u30E5\u30E1\u30F3\u30C8 URL",
    description: "\u8AAC\u660E",
    features: "\u7279\u5FB4",
    specification: "\u4ED5\u69D8",
    preview: "Preview \u672A\u4FDD\u5B58\u306E\u5909\u66F4",
    current: "\u73FE\u5728",
    archivedStatus: "\u30A2\u30FC\u30AB\u30A4\u30D6\u3055\u308C\u305F",
},
"ko-KR": {
    cloned: (source: string, created: string) => `\uBCF5\uC81C\uB428${source}~\uCC98\uB7FC${created}. \uD074\uB860\uC740 Hidden\uC785\uB2C8\uB2E4.`,
    saved: (part: string, revision: number) => `\uC800\uC7A5\uB428${part}\uAC1C\uC815${revision}.`,
    created: (part: string) => `\uC0DD\uC131\uB428${part}Hidden\uB85C.`,
    mutated: (part: string, action: string) => `${part} ${action === "\uC228\uB2E4" ? "\uC228\uACA8\uC9C4" : "\uBCF4\uAD00\uB41C"}.`,
    published: (part: string, revision: number) => `${part}\uAC8C\uC2DC\uAC00 \uAC1C\uC815 \uB300\uAE30 \uC911\uC774\uC5C8\uC2B5\uB2C8\uB2E4.${revision}.`,
    exportDownloaded: "Product \uB0B4\uBCF4\uB0B4\uAE30\uAC00 \uB2E4\uC6B4\uB85C\uB4DC\uB418\uC5C8\uC2B5\uB2C8\uB2E4.",
    products: "\uC81C\uD488",
    includeArchived: "\uBCF4\uAD00\uB41C \uD56D\uBAA9 \uD3EC\uD568",
    export: "XLSX \uB0B4\uBCF4\uB0B4\uAE30",
    refresh: "\uC0C8\uB85C \uACE0\uCE58\uB2E4",
    newProduct: "\uC2E0\uC81C\uD488",
    partNumber: "\uBD80\uD488 \uBC88\uD638",
    name: "\uC774\uB984",
    manufacturer: "\uC81C\uC870\uC5C5\uCCB4",
    category: "\uBC94\uC8FC",
    state: "\uC0C1\uD0DC",
    actions: "\uD589\uC704",
    edit: "\uD3B8\uC9D1\uD558\uB2E4",
    data: "\uB370\uC774\uD130",
    translations: "\uBC88\uC5ED",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Admin UI \uC5B8\uC5B4\uAC00 \uC544\uB2CC \uD604\uC7AC Website Site Default\uC758 \uAE30\uBCF8\uAC12\uC785\uB2C8\uB2E4. \uC774 Product\uC5D0 \uB300\uD574 \uC774\uB97C \uC7AC\uC815\uC758\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
    clone: "\uD074\uB860",
    publishConfirm: "Publish \uC774 \uC81C\uD488\uC740\uC694?",
    publishDescription: "\uC804\uCCB4 Product \uAC8C\uC2DC \uB2E8\uC704\uB294 \uD65C\uC131\uD654 \uD6C4 \uACF5\uAC1C\uB429\uB2C8\uB2E4.",
    publish: "Publish",
    hideConfirm: "\uC0C8\uB85C\uC6B4 \uACF5\uAC1C \uC694\uCCAD\uC5D0\uC11C \uC774 \uC81C\uD488\uC744 \uC228\uAE30\uC2DC\uACA0\uC2B5\uB2C8\uAE4C?",
    hide: "\uC228\uB2E4",
    archiveConfirm: "\uC774 \uC81C\uD488\uC744 \uBCF4\uAD00\uD558\uC2DC\uACA0\uC2B5\uB2C8\uAE4C? Archived \uB808\uCF54\uB4DC\uB294 \uC77D\uAE30 \uC804\uC6A9\uC785\uB2C8\uB2E4.",
    archive: "\uBCF4\uAD00\uC18C",
    editTitle: (part: string) => `\uD3B8\uC9D1\uD558\uB2E4${part}`,
    cloneTitle: (part: string) => `\uD074\uB860${part}`,
    save: "\uAD6C\uD558\uB2E4",
    createClone: "Hidden \uD074\uB860 \uC0DD\uC131",
    createHidden: "Hidden \uC81C\uD488 \uC0DD\uC131",
    publicTitle: "\uC774 Product\uB294 \uD604\uC7AC \uACF5\uAC1C\uB418\uC5B4 \uC788\uC2B5\uB2C8\uB2E4.",
    publicDescription: "\uC800\uC7A5\uD558\uBA74 \uC0C8\uB85C\uC6B4 \uACF5\uAC1C \uBC84\uC804\uC774 \uC0DD\uC131\uB429\uB2C8\uB2E4. \uC804\uCCB4 \uB300\uCCB4 \uCD9C\uD310 \uB2E8\uC704\uAC00 \uD65C\uC131\uD654\uB420 \uB54C\uAE4C\uC9C0 \uD604\uC7AC \uAC1C\uC815\uD310\uC744 \uACC4\uC18D \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
    cloneInfo: "\uB3C5\uB9BD\uC801\uC778 Hidden \uD074\uB860 \uC0DD\uC131",
    cloneDescription: "\uC0C8 \uBD80\uD488 \uBC88\uD638\uB97C \uC785\uB825\uD558\uC138\uC694. Product \uB370\uC774\uD130\uC640 \uC720\uD6A8\uD55C \uC790\uC0B0, \uC774\uBBF8\uC9C0, \uBB38\uC11C, \uC0AC\uC591 \uBC0F \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uCC38\uC870\uB294 \uC18C\uC2A4\uC5D0\uC11C \uBCF5\uC0AC\uB429\uB2C8\uB2E4.",
    slug: "URL \uC2AC\uB7EC\uADF8",
    slugEdit: "\uC774\uB97C \uBCC0\uACBD\uD558\uBA74 \uACF5\uAC1C URL\uAC00 \uBCC0\uACBD\uB429\uB2C8\uB2E4.",
    slugCreate: "\uC548\uC815\uC801\uC778 \uC81C\uC548\uC744 \uD55C \uBC88 \uC0DD\uC131\uD558\uB824\uBA74 \uBE44\uC6CC \uB450\uC138\uC694.",
    autoGenerated: "\uC790\uB3D9 \uC0DD\uC131",
    customPath: "\uC0AC\uC6A9\uC790 \uC815\uC758 \uACF5\uAC1C \uACBD\uB85C",
    customPathHelp: "\uC120\uD0DD\uC801 \uC804\uCCB4 \uB0B4\uBD80 \uACBD\uB85C. \uC804\uC5ED \uD328\uD134\uC774 \uBCC0\uACBD\uB418\uBA74 \uACE0\uC815\uB41C \uC0C1\uD0DC\uB85C \uC720\uC9C0\uB429\uB2C8\uB2E4.",
    customPathPlaceholder: "/\uD2B9\uC9D1/\uC608",
    productName: "Product \uC774\uB984",
    brand: "\uC0C1\uD45C",
    applications: "\uC751\uC6A9",
    lifecycle: "\uC218\uBA85\uC8FC\uAE30",
    package: "\uD328\uD0A4\uC9C0/\uD3FC \uD329\uD130",
    visibility: "\uC2DC\uACC4",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "\uB808\uAC70\uC2DC \uBB38\uC11C URL",
    description: "\uC124\uBA85",
    features: "\uD2B9\uC9D5",
    specification: "\uC0AC\uC591",
    preview: "Preview \uC800\uC7A5\uB418\uC9C0 \uC54A\uC740 \uBCC0\uACBD \uC0AC\uD56D",
    current: "\uD604\uC7AC\uC758",
    archivedStatus: "\uBCF4\uAD00\uB41C",
},
"de-DE": {
    cloned: (source: string, created: string) => `Geklont${source}als${created}. Der Klon ist Hidden.`,
    saved: (part: string, revision: number) => `Gespeichert${part}Revision${revision}.`,
    created: (part: string) => `Erstellt${part}als Hidden.`,
    mutated: (part: string, action: string) => `${part} ${action === "verstecken" ? "versteckt" : "archiviert"}.`,
    published: (part: string, revision: number) => `${part}Die Ver\u00F6ffentlichung wurde bei der \u00DCberarbeitung in die Warteschlange gestellt${revision}.`,
    exportDownloaded: "Product-Export heruntergeladen.",
    products: "Produkte",
    includeArchived: "Archiviert einschlie\u00DFen",
    export: "Exportieren Sie XLSX",
    refresh: "Aktualisieren",
    newProduct: "Neues Produkt",
    partNumber: "Teilenummer",
    name: "Name",
    manufacturer: "Hersteller",
    category: "Kategorie",
    state: "Zustand",
    actions: "Aktionen",
    edit: "Bearbeiten",
    data: "Daten",
    translations: "\u00DCbersetzungen",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Standardwerte aus dem aktuellen Website Site Default, nicht aus Ihrer Admin UI-Sprache. Sie k\u00F6nnen es f\u00FCr diesen Product \u00FCberschreiben.",
    clone: "Klon",
    publishConfirm: "Publish dieses Produkt?",
    publishDescription: "Die komplette Product-Publikationseinheit wird nach der Aktivierung \u00F6ffentlich zug\u00E4nglich gemacht.",
    publish: "Publish",
    hideConfirm: "Dieses Produkt vor neuen \u00F6ffentlichen Anfragen verbergen?",
    hide: "Verstecken",
    archiveConfirm: "Dieses Produkt archivieren? Archived-Datens\u00E4tze sind schreibgesch\u00FCtzt.",
    archive: "Archiv",
    editTitle: (part: string) => `Bearbeiten${part}`,
    cloneTitle: (part: string) => `Klon${part}`,
    save: "Speichern",
    createClone: "Erstellen Sie einen Hidden-Klon",
    createHidden: "Erstellen Sie das Produkt Hidden",
    publicTitle: "Dieser Product ist derzeit \u00F6ffentlich",
    publicDescription: "Beim Speichern wird eine neue \u00F6ffentliche Revision erstellt. Die aktuelle Revision bleibt verf\u00FCgbar, bis die vollst\u00E4ndige Ersatzpublikationseinheit aktiviert wird.",
    cloneInfo: "Erstellen Sie einen unabh\u00E4ngigen Hidden-Klon",
    cloneDescription: "Geben Sie eine neue Teilenummer ein. Product-Daten und g\u00FCltige Asset-, Bild-, Dokument-, Spezifikations- und Anwendungsreferenzen werden aus der Quelle kopiert.",
    slug: "URL Schnecke",
    slugEdit: "Wenn Sie dies \u00E4ndern, \u00E4ndert sich das \u00F6ffentliche URL.",
    slugCreate: "Lassen Sie das Feld leer, um einmal einen stabilen Vorschlag zu generieren.",
    autoGenerated: "automatisch generiert",
    customPath: "Benutzerdefinierter \u00F6ffentlicher Pfad",
    customPathHelp: "Optionaler vollst\u00E4ndiger interner Pfad; es bleibt unver\u00E4ndert, wenn sich das globale Muster \u00E4ndert.",
    customPathPlaceholder: "/empfohlen/Beispiel",
    productName: "Product-Name",
    brand: "Marke",
    applications: "Anwendungen",
    lifecycle: "Lebenszyklus",
    package: "Paket/Formfaktor",
    visibility: "Sichtweite",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Legacy-Dokument URL",
    description: "Beschreibung",
    features: "Merkmale",
    specification: "Spezifikation",
    preview: "Preview nicht gespeicherte \u00C4nderungen",
    current: "aktuell",
    archivedStatus: "archiviert",
},
"fr-FR": {
    cloned: (source: string, created: string) => `Clon\u00E9${source}comme${created}. Le clone est Hidden.`,
    saved: (part: string, revision: number) => `Enregistr\u00E9${part}r\u00E9vision${revision}.`,
    created: (part: string) => `Cr\u00E9\u00E9${part}comme Hidden.`,
    mutated: (part: string, action: string) => `${part} ${action === "cacher" ? "cach\u00E9" : "archiv\u00E9"}.`,
    published: (part: string, revision: number) => `${part}la publication a \u00E9t\u00E9 mise en file d'attente lors de la r\u00E9vision${revision}.`,
    exportDownloaded: "Exportation Product t\u00E9l\u00E9charg\u00E9e.",
    products: "Produits",
    includeArchived: "Inclure archiv\u00E9",
    export: "Exporter XLSX",
    refresh: "Rafra\u00EEchir",
    newProduct: "Nouveau produit",
    partNumber: "Num\u00E9ro de pi\u00E8ce",
    name: "Nom",
    manufacturer: "Fabricant",
    category: "Cat\u00E9gorie",
    state: "\u00C9tat",
    actions: "Actes",
    edit: "Modifier",
    data: "Donn\u00E9es",
    translations: "Traductions",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Valeurs par d\u00E9faut du Website Site Default actuel, et non de la langue de votre interface utilisateur Admin. Vous pouvez le remplacer pour ce Product.",
    clone: "Cloner",
    publishConfirm: "Publish ce produit?",
    publishDescription: "L'unit\u00E9 de publication compl\u00E8te Product deviendra publique apr\u00E8s activation.",
    publish: "Publish",
    hideConfirm: "Masquer ce produit aux nouvelles demandes publiques\u00A0?",
    hide: "Cacher",
    archiveConfirm: "Archiver ce produit\u00A0? Les enregistrements Archived sont en lecture seule.",
    archive: "Archive",
    editTitle: (part: string) => `Modifier${part}`,
    cloneTitle: (part: string) => `Cloner${part}`,
    save: "Sauvegarder",
    createClone: "Cr\u00E9er un clone Hidden",
    createHidden: "Cr\u00E9er un produit Hidden",
    publicTitle: "Ce Product est actuellement public",
    publicDescription: "L'enregistrement cr\u00E9e une nouvelle r\u00E9vision publique. La r\u00E9vision actuelle reste disponible jusqu'\u00E0 ce que l'unit\u00E9 de publication de remplacement compl\u00E8te soit activ\u00E9e.",
    cloneInfo: "Cr\u00E9er un clone Hidden ind\u00E9pendant",
    cloneDescription: "Entrez un nouveau num\u00E9ro de pi\u00E8ce. Les donn\u00E9es Product et les r\u00E9f\u00E9rences valides d'actifs, d'images, de documents, de sp\u00E9cifications et d'applications sont copi\u00E9es \u00E0 partir de la source.",
    slug: "Limace URL",
    slugEdit: "Changer cela modifie le URL public.",
    slugCreate: "Laissez vide pour g\u00E9n\u00E9rer une suggestion stable une fois.",
    autoGenerated: "g\u00E9n\u00E9r\u00E9 automatiquement",
    customPath: "Chemin public personnalis\u00E9",
    customPathHelp: "Chemin interne complet facultatif\u00A0; il reste fixe lorsque le mod\u00E8le global change.",
    customPathPlaceholder: "/en vedette/exemple",
    productName: "Nom Product",
    brand: "Marque",
    applications: "Applications",
    lifecycle: "Cycle de vie",
    package: "Emballage/facteur de forme",
    visibility: "Visibilit\u00E9",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Ancien document URL",
    description: "Description",
    features: "Caract\u00E9ristiques",
    specification: "Sp\u00E9cification",
    preview: "Modifications non enregistr\u00E9es Preview",
    current: "actuel",
    archivedStatus: "archiv\u00E9",
},
"it-IT": {
    cloned: (source: string, created: string) => `Clonato${source}COME${created}. Il clone \u00E8 Hidden.`,
    saved: (part: string, revision: number) => `Salvato${part}revisione${revision}.`,
    created: (part: string) => `Creato${part}come Hidden.`,
    mutated: (part: string, action: string) => `${part} ${action === "nascondere" ? "nascosto" : "archiviato"}.`,
    published: (part: string, revision: number) => `${part}la pubblicazione \u00E8 stata accodata alla revisione${revision}.`,
    exportDownloaded: "Esportazione Product scaricata.",
    products: "Prodotti",
    includeArchived: "Includi archiviato",
    export: "Esporta XLSX",
    refresh: "Aggiorna",
    newProduct: "Nuovo prodotto",
    partNumber: "Numero di parte",
    name: "Nome",
    manufacturer: "Produttore",
    category: "Categoria",
    state: "Stato",
    actions: "Azioni",
    edit: "Modificare",
    data: "Dati",
    translations: "Traduzioni",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Impostazioni predefinite dall'attuale Website Site Default, non dalla lingua dell'interfaccia utente Admin. Puoi sovrascriverlo per questo Product.",
    clone: "Clone",
    publishConfirm: "Publish questo prodotto?",
    publishDescription: "L'unit\u00E0 di pubblicazione completa Product diventer\u00E0 pubblica dopo l'attivazione.",
    publish: "Publish",
    hideConfirm: "Nascondere questo prodotto dalle nuove richieste pubbliche?",
    hide: "Nascondere",
    archiveConfirm: "Archiviare questo prodotto? I record Archived sono di sola lettura.",
    archive: "Archivio",
    editTitle: (part: string) => `Modificare${part}`,
    cloneTitle: (part: string) => `Clone${part}`,
    save: "Salva",
    createClone: "Crea clone Hidden",
    createHidden: "Crea il prodotto Hidden",
    publicTitle: "Questo Product \u00E8 attualmente pubblico",
    publicDescription: "Il salvataggio crea una nuova revisione pubblica. La revisione corrente rimane disponibile fino all'attivazione dell'unit\u00E0 di pubblicazione sostitutiva completa.",
    cloneInfo: "Crea un clone Hidden indipendente",
    cloneDescription: "Inserisci un nuovo codice prodotto. I dati Product e i riferimenti validi a risorse, immagini, documenti, specifiche e applicazioni vengono copiati dall'origine.",
    slug: "Lumaca URL",
    slugEdit: "Cambiando questo cambia lo URL pubblico.",
    slugCreate: "Lascia vuoto per generare un suggerimento stabile una volta.",
    autoGenerated: "generato automaticamente",
    customPath: "Percorso pubblico personalizzato",
    customPathHelp: "Percorso interno completo opzionale; rimane fisso quando cambia il modello globale.",
    customPathPlaceholder: "/in primo piano/esempio",
    productName: "Nome Product",
    brand: "Marca",
    applications: "Applicazioni",
    lifecycle: "Ciclo vitale",
    package: "Pacchetto/fattore di forma",
    visibility: "Visibilit\u00E0",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Documento preesistente URL",
    description: "Descrizione",
    features: "Caratteristiche",
    specification: "Specifica",
    preview: "Preview modifiche non salvate",
    current: "attuale",
    archivedStatus: "archiviato",
},
"es-ES": {
    cloned: (source: string, created: string) => `clonado${source}como${created}. El clon es Hidden.`,
    saved: (part: string, revision: number) => `Guardado${part}revisi\u00F3n${revision}.`,
    created: (part: string) => `Creado${part}como Hidden.`,
    mutated: (part: string, action: string) => `${part} ${action === "esconder" ? "oculto" : "archivado"}.`,
    published: (part: string, revision: number) => `${part}la publicaci\u00F3n estaba en cola en la revisi\u00F3n${revision}.`,
    exportDownloaded: "Exportaci\u00F3n Product descargada.",
    products: "Productos",
    includeArchived: "Incluir archivado",
    export: "Exportar XLSX",
    refresh: "Refrescar",
    newProduct: "Nuevo producto",
    partNumber: "N\u00FAmero de pieza",
    name: "Nombre",
    manufacturer: "Fabricante",
    category: "Categor\u00EDa",
    state: "Estado",
    actions: "Comportamiento",
    edit: "Editar",
    data: "Datos",
    translations: "Traducciones",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Los valores predeterminados son del Website Site Default actual, no del idioma de la interfaz de usuario de Admin. Puede anularlo para este Product.",
    clone: "Clon",
    publishConfirm: "Publish este producto?",
    publishDescription: "La unidad de publicaci\u00F3n completa Product se har\u00E1 p\u00FAblica despu\u00E9s de la activaci\u00F3n.",
    publish: "Publish",
    hideConfirm: "\u00BFOcultar este producto de nuevas solicitudes p\u00FAblicas?",
    hide: "Esconder",
    archiveConfirm: "\u00BFArchivar este producto? Los registros Archived son de solo lectura.",
    archive: "Archivo",
    editTitle: (part: string) => `Editar${part}`,
    cloneTitle: (part: string) => `Clon${part}`,
    save: "Ahorrar",
    createClone: "Crear clon Hidden",
    createHidden: "Crear producto Hidden",
    publicTitle: "Este Product es actualmente p\u00FAblico.",
    publicDescription: "Al guardar se crea una nueva revisi\u00F3n p\u00FAblica. La revisi\u00F3n actual permanece disponible hasta que se active la unidad de publicaci\u00F3n de reemplazo completa.",
    cloneInfo: "Crea un clon Hidden independiente",
    cloneDescription: "Ingrese un nuevo n\u00FAmero de pieza. Los datos Product y las referencias v\u00E1lidas de activos, im\u00E1genes, documentos, especificaciones y aplicaciones se copian de la fuente.",
    slug: "Babosa URL",
    slugEdit: "Cambiar esto cambia el p\u00FAblico URL.",
    slugCreate: "D\u00E9jelo en blanco para generar una sugerencia estable una vez.",
    autoGenerated: "generado autom\u00E1ticamente",
    customPath: "Ruta p\u00FAblica personalizada",
    customPathHelp: "Ruta interna completa opcional; permanece fijo cuando cambia el patr\u00F3n global.",
    customPathPlaceholder: "/destacado/ejemplo",
    productName: "Nombre Product",
    brand: "Marca",
    applications: "Aplicaciones",
    lifecycle: "Ciclo vital",
    package: "Paquete/factor de forma",
    visibility: "Visibilidad",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Documento heredado URL",
    description: "Descripci\u00F3n",
    features: "Caracter\u00EDsticas",
    specification: "Especificaci\u00F3n",
    preview: "Preview cambios no guardados",
    current: "actual",
    archivedStatus: "archivado",
},
"pt-BR": {
    cloned: (source: string, created: string) => `Clonado${source}como${created}. O clone \u00E9 Hidden.`,
    saved: (part: string, revision: number) => `Salvo${part}revis\u00E3o${revision}.`,
    created: (part: string) => `Criado${part}como Hidden.`,
    mutated: (part: string, action: string) => `${part} ${action === "esconder" ? "escondido" : "arquivado"}.`,
    published: (part: string, revision: number) => `${part}a publica\u00E7\u00E3o estava na fila de revis\u00E3o${revision}.`,
    exportDownloaded: "Exporta\u00E7\u00E3o Product baixada.",
    products: "Produtos",
    includeArchived: "Incluir arquivado",
    export: "Exportar XLSX",
    refresh: "Atualizar",
    newProduct: "Novo produto",
    partNumber: "N\u00FAmero da pe\u00E7a",
    name: "Nome",
    manufacturer: "Fabricante",
    category: "Categoria",
    state: "Estado",
    actions: "A\u00E7\u00F5es",
    edit: "Editar",
    data: "Dados",
    translations: "Tradu\u00E7\u00F5es",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "O padr\u00E3o \u00E9 o Website Site Default atual, n\u00E3o o idioma da interface do usu\u00E1rio Admin. Voc\u00EA pode substitu\u00ED-lo por este Product.",
    clone: "Clone",
    publishConfirm: "Publish este produto?",
    publishDescription: "A unidade de publica\u00E7\u00E3o Product completa se tornar\u00E1 p\u00FAblica ap\u00F3s a ativa\u00E7\u00E3o.",
    publish: "Publish",
    hideConfirm: "Ocultar este produto de novas solicita\u00E7\u00F5es p\u00FAblicas?",
    hide: "Esconder",
    archiveConfirm: "Arquivar este produto? Os registros Archived s\u00E3o somente leitura.",
    archive: "Arquivo",
    editTitle: (part: string) => `Editar${part}`,
    cloneTitle: (part: string) => `Clone${part}`,
    save: "Salvar",
    createClone: "Criar clone Hidden",
    createHidden: "Criar produto Hidden",
    publicTitle: "Este Product \u00E9 atualmente p\u00FAblico",
    publicDescription: "Salvar cria uma nova revis\u00E3o p\u00FAblica. A revis\u00E3o atual permanece dispon\u00EDvel at\u00E9 que a unidade de publica\u00E7\u00E3o de substitui\u00E7\u00E3o completa seja ativada.",
    cloneInfo: "Crie um clone Hidden independente",
    cloneDescription: "Insira um novo n\u00FAmero de pe\u00E7a. Os dados Product e refer\u00EAncias v\u00E1lidas de ativos, imagens, documentos, especifica\u00E7\u00F5es e aplicativos s\u00E3o copiados da origem.",
    slug: "Lesma URL",
    slugEdit: "Alterar isso altera o URL p\u00FAblico.",
    slugCreate: "Deixe em branco para gerar uma sugest\u00E3o est\u00E1vel uma vez.",
    autoGenerated: "gerado automaticamente",
    customPath: "Caminho p\u00FAblico personalizado",
    customPathHelp: "Caminho interno completo opcional; permanece fixo quando o padr\u00E3o global muda.",
    customPathPlaceholder: "/destaque/exemplo",
    productName: "Nome Product",
    brand: "Marca",
    applications: "Aplicativos",
    lifecycle: "Vida \u00FAtil",
    package: "Pacote/fator de forma",
    visibility: "Visibilidade",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Documento legado URL",
    description: "Descri\u00E7\u00E3o",
    features: "Caracter\u00EDsticas",
    specification: "Especifica\u00E7\u00E3o",
    preview: "Preview altera\u00E7\u00F5es n\u00E3o salvas",
    current: "atual",
    archivedStatus: "arquivado",
},
};

const blankProduct: ProductForm = {
  slug: "",
  custom_path: "",
  part_number: "",
  name: "",
  category_id: "cat_uncategorized",
  description: "",
  specification: "",
  document_url: "",
  status: "hidden",
};

export function CatalogPanel({
  locale,
  onError,
  onMessage,
}: Feedback & { locale: CatalogLocale }) {
  const text = labels[locale];
  const { capabilities } = useAdminIdentity();
  const canEdit = Boolean(capabilities["catalog.edit"]);
  const canPublish = Boolean(capabilities["catalog.publish"]);
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState<{ field: string; order: "asc" | "desc" }>({ field: "updated_at", order: "desc" });
  const invalidate = useInvalidate();
  const [categories, setCategories] = useState<Category[]>([]);
  const [manufacturers, setManufacturers] = useState<DictionaryEntry[]>([]);
  const [brands, setBrands] = useState<DictionaryEntry[]>([]);
  const [applications, setApplications] = useState<DictionaryEntry[]>([]);
  const [lifecycles, setLifecycles] = useState<DictionaryEntry[]>([]);
  const [includeArchived, setIncludeArchived] = useState(false);
  const [lookupLoading, setLookupLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState<string>();
  const { query, result } = useList<Product, APIError>({
    resource: "products", pagination: { currentPage: page, pageSize: 20 },
    filters: [{ field: "include_archived", operator: "eq", value: includeArchived }],
    sorters: [sort], queryOptions: { retry: false },
  });
  const products = result.data;
  const loading = lookupLoading || query.isFetching;
  useEffect(() => { if (query.error) onError(query.error); }, [query.error]);
  const [exporting, setExporting] = useState(false);
  const [editing, setEditing] = useState<Product>();
  const [cloning, setCloning] = useState<Product>();
  const [dataProduct, setDataProduct] = useState<Product>();
  const [translationProduct, setTranslationProduct] = useState<Product>();
  const [siteSettings, setSiteSettings] = useState<SiteSettings>();
  const [formOpen, setFormOpen] = useState(false);
  const [form] = Form.useForm<ProductForm>();

  const exportProducts = async () => {
    setExporting(true);
    try {
      await catalogCommands.export();
      onMessage(text.exportDownloaded);
    } catch (error) {
      onError(error);
    } finally {
      setExporting(false);
    }
  };

  const loadLookups = async () => {
    setLookupLoading(true);
    try {
      const [categoryRows, manufacturerRows, brandRows, applicationRows, lifecycleRows, settings] = await catalogCommands.lookups();
      setCategories(categoryRows ?? []);
      setManufacturers(manufacturerRows ?? []);
      setBrands(brandRows ?? []);
      setApplications(applicationRows ?? []);
      setLifecycles(lifecycleRows ?? []);
      setSiteSettings(settings);
    } catch (error) { onError(error); }
    finally { setLookupLoading(false); }
  };
  // Refetch updates only the server snapshot, never the open form or revision.
  const load = async () => {
    await invalidate({ resource: "products", invalidates: ["list", "detail"] });
    await loadLookups();
  };
  useEffect(() => { void loadLookups(); }, []);

  const categoryOptions = useMemo(
    () =>
      categories
        .filter((item) => item.status === "active")
        .map((item) => ({ value: item.id, label: item.name })),
    [categories],
  );
  const dictionaryOptions = (rows: DictionaryEntry[]) =>
    rows
      .filter((item) => item.status === "active")
      .map((item) => ({ value: item.id, label: item.name }));

  const beginCreate = () => {
    setFormError(undefined);
    setEditing(undefined);
    setCloning(undefined);
    form.setFieldsValue({ ...blankProduct, source_locale: siteSettings?.default_locale ?? "en-US" });
    setFormOpen(true);
  };

  const beginEdit = (product: Product) => {
    setFormError(undefined);
    setEditing(product);
    setCloning(undefined);
    form.setFieldsValue({
      slug: product.slug,
      custom_path: product.custom_path,
      part_number: product.part_number,
      name: product.name,
      manufacturer_id: product.manufacturer_id,
      manufacturer: product.manufacturer,
      brand_id: product.brand_id,
      brand: product.brand,
      application_ids: product.application_ids ?? [],
      lifecycle_id: product.lifecycle_id,
      category_id: product.category_id,
      package_form_factor: product.package_form_factor,
      description: product.description,
      features: product.features,
      specification: product.specification,
      document_url: product.document_url,
      status: product.status,
    });
    setFormOpen(true);
  };

  const beginClone = (product: Product) => {
    setFormError(undefined);
    setEditing(undefined);
    setCloning(product);
    form.setFieldsValue({
      slug: "",
      custom_path: "",
      part_number: "",
      name: product.name,
      manufacturer_id: product.manufacturer_id,
      manufacturer: product.manufacturer,
      brand_id: product.brand_id,
      brand: product.brand,
      application_ids: product.application_ids ?? [],
      lifecycle_id: product.lifecycle_id,
      category_id: product.category_id,
      package_form_factor: product.package_form_factor,
      description: product.description,
      features: product.features,
      specification: product.specification,
      document_url: product.document_url,
      status: "hidden",
    });
    setFormOpen(true);
  };

  const save = async (values: ProductForm) => {
    if (saving) return;
    setSaving(true);
    setFormError(undefined);
    try {
      if (cloning) {
        const created = await catalogCommands.clone(cloning, values);
        onMessage(text.cloned(cloning.part_number, created.part_number));
      } else if (editing) {
        const { data: saved } = await dataProvider.update<Product, { expected_revision: number; product: Product }>({
          resource: "products", id: editing.id,
          variables: { expected_revision: editing.revision, product: { ...editing, ...values, status: editing.status } },
        });
        // URL changes have a separate command/commit. Keep the successful source
        // revision if that second operation fails, along with the unsaved URL.
        setEditing(saved);
        onMessage(text.saved(saved.part_number, saved.revision));
        if (values.slug !== saved.slug || (values.custom_path ?? "") !== (saved.custom_path ?? "")) {
          try { await catalogCommands.changeURL(saved, values); }
          catch (error) {
            setFormError(`${text.saved(saved.part_number, saved.revision)} ${urlSaveUnconfirmedText[locale]} ${error instanceof Error ? error.message : String(error)}`);
            return;
          }
        }
      } else {
        const { data: created } = await dataProvider.create<Product, ProductForm>({ resource: "products", variables: values });
        onMessage(text.created(created.part_number));
      }
      setEditing(undefined);
      setCloning(undefined);
      setFormOpen(false);
      form.resetFields();
    } catch (error) {
      // 409 preserves the original input and expected revision. No blind retry.
      setFormError(error instanceof Error ? error.message : String(error));
      onError(error);
      return;
    } finally {
      setSaving(false);
      void load();
    }
  };

  const previewUnsaved = async () => {
    let previewWindow: Window | null = null;
    try {
      const values = await form.validateFields();
      previewWindow = window.open("about:blank", "_blank");
      const receipt = await catalogCommands.preview(editing, values);
      if (previewWindow) {
        previewWindow.location.assign(receipt.url);
      } else {
        window.open(receipt.url, "_blank", "noopener,noreferrer");
      }
    } catch (error) {
      previewWindow?.close();
      onError(error);
    }
  };

  const mutate = async (product: Product, action: "hide" | "archive") => {
    try {
      await catalogCommands[action](product);
      onMessage(text.mutated(product.part_number, action));
      await load();
    } catch (error) {
      onError(error);
      await load();
    }
  };

  const publish = async (product: Product) => {
    try {
      const updated = await catalogCommands.publish(product);
      onMessage(text.published(updated.part_number, updated.revision));
      await load();
    } catch (error) {
      onError(error);
      await load();
    }
  };

  return (
    <Space direction="vertical" size="large" className="panel-stack">
      <Card
        title={text.products}
        extra={
          <Space wrap>
            <Checkbox
              checked={includeArchived}
              onChange={(event) => { setIncludeArchived(event.target.checked); setPage(1); }}
            >
              {text.includeArchived}
            </Checkbox>
            <Button disabled={!capabilities["catalog.export"]} loading={exporting} onClick={() => void exportProducts()}>
              {text.export}
            </Button>
            <Button onClick={() => void load()}>{text.refresh}</Button>
            <Button type="primary" disabled={!canEdit || !siteSettings} onClick={beginCreate}>
              {text.newProduct}
            </Button>
          </Space>
        }
      >
        <Table<Product>
          rowKey="id"
          loading={loading}
          dataSource={products}
          pagination={{ current: page, pageSize: 20, total: result.total ?? 0, showSizeChanger: false, hideOnSinglePage: true }}
          onChange={(pagination, _filters, sorter, extra) => {
            setPage(extra.action === "sort" ? 1 : pagination.current ?? 1);
            if (!Array.isArray(sorter)) setSort(sorter.order ? { field: String(sorter.field), order: sorter.order === "ascend" ? "asc" : "desc" } : { field: "updated_at", order: "desc" });
          }}
          scroll={{ x: 880 }}
          columns={[
            {
              title: text.partNumber,
              dataIndex: "part_number",
              sorter: true,
              sortOrder: sort.field === "part_number" ? (sort.order === "asc" ? "ascend" : "descend") : null,
            },
            {
              title: text.name,
              dataIndex: "name",
              sorter: true,
              sortOrder: sort.field === "name" ? (sort.order === "asc" ? "ascend" : "descend") : null,
              render: (value: string) =>
                value || <Typography.Text type="secondary">—</Typography.Text>,
            },
            {
              title: text.manufacturer,
              render: (_, row) =>
                row.manufacturer || row.manufacturer_id || "—",
            },
            {
              title: text.category,
              render: (_, row) =>
                categories.find((item) => item.id === row.category_id)?.name ??
                row.category_id,
            },
            {
              title: text.state,
              render: (_, row) => (
                <Space>
                  <Tag
                    color={row.record_state === "archived" ? "default" : "blue"}
                  >
                    {row.record_state === "archived"
                      ? text.archivedStatus
                      : text.current}
                  </Tag>
                  <Tag color={row.status === "published" ? "green" : "gold"}>
                    {row.status === "published"
                      ? text.publishedStatus
                      : text.hidden}
                  </Tag>
                  <Typography.Text type="secondary">
                    r{row.revision}
                  </Typography.Text>
                </Space>
              ),
            },
            {
              title: text.actions,
              fixed: "right",
              render: (_, row) => (
                <Space>
                  <Button
                    size="small"
                    disabled={!canEdit || row.record_state === "archived"}
                    onClick={() => beginEdit(row)}
                  >
                    {text.edit}
                  </Button>
                  <Button
                    size="small"
                    disabled={!canEdit || row.record_state === "archived"}
                    onClick={() => setDataProduct(row)}
                  >
                    {text.data}
                  </Button>
                  {siteSettings?.content_multilingual_enabled && (
                    <Button
                      size="small"
                      disabled={!canEdit || row.record_state === "archived"}
                      onClick={() => setTranslationProduct(row)}
                    >
                      {text.translations}
                    </Button>
                  )}
                  <Button size="small" disabled={!canEdit || !siteSettings} onClick={() => beginClone(row)}>
                    {text.clone}
                  </Button>
                  {canPublish && canEdit && row.record_state !== "archived" &&
                    row.status === "hidden" && (
                      <Popconfirm
                        title={text.publishConfirm}
                        description={text.publishDescription}
                        onConfirm={() => void publish(row)}
                      >
                        <Button size="small" type="primary">
                          {text.publish}
                        </Button>
                      </Popconfirm>
                    )}
                  {canPublish && row.record_state !== "archived" &&
                    row.status === "published" && (
                      <Popconfirm
                        title={text.hideConfirm}
                        onConfirm={() => void mutate(row, "hide")}
                      >
                        <Button size="small">{text.hide}</Button>
                      </Popconfirm>
                    )}
                  {canPublish && row.record_state !== "archived" && (
                    <Popconfirm
                      title={text.archiveConfirm}
                      onConfirm={() => void mutate(row, "archive")}
                    >
                      <Button size="small" danger>
                        {text.archive}
                      </Button>
                    </Popconfirm>
                  )}
                </Space>
              ),
            },
          ]}
        />
      </Card>

      <Modal
        open={formOpen}
        title={
          editing
            ? text.editTitle(editing.part_number)
            : cloning
              ? text.cloneTitle(cloning.part_number)
              : text.newProduct
        }
        okText={
          editing ? text.save : cloning ? text.createClone : text.createHidden
        }
        confirmLoading={saving}
        closable={!saving}
        maskClosable={!saving}
        cancelButtonProps={{ disabled: saving }}
        onOk={() => form.submit()}
        onCancel={() => {
          setEditing(undefined);
          setCloning(undefined);
          setFormOpen(false);
          form.resetFields();
        }}
        width={760}
        destroyOnHidden
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={(values) => void save(values)}
          initialValues={blankProduct}
        >
          {formError && <Alert className="bottom-gap" type="error" showIcon title={formError} />}
          {editing?.status === "published" ? (
            <Alert
              className="bottom-gap"
              type="warning"
              showIcon
              message={text.publicTitle}
              description={text.publicDescription}
            />
          ) : null}
          {cloning ? (
            <Alert
              className="bottom-gap"
              type="info"
              showIcon
              message={text.cloneInfo}
              description={text.cloneDescription}
            />
          ) : null}
          <div className="form-grid">
            <Form.Item
              name="part_number"
              label={text.partNumber}
              rules={[{ required: true }]}
            >
              <Input />
            </Form.Item>
            <Form.Item
              name="slug"
              label={text.slug}
              extra={editing ? text.slugEdit : text.slugCreate}
            >
              <Input placeholder={text.autoGenerated} />
            </Form.Item>
            <Form.Item
              name="custom_path"
              label={text.customPath}
              extra={text.customPathHelp}
            >
              <Input placeholder={text.customPathPlaceholder} />
            </Form.Item>
            <Form.Item name="name" label={text.productName}>
              <Input />
            </Form.Item>
            {!editing && !cloning ? (
              <Form.Item name="source_locale" label={text.sourceLocale} extra={text.sourceLocaleHelp} rules={[{ required: true }]}>
                <Select options={localeSelectOptions(siteSettings?.supported_locales ?? [])} />
              </Form.Item>
            ) : null}
            <Form.Item name="manufacturer_id" label={text.manufacturer}>
              <Select
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(manufacturers)}
              />
            </Form.Item>
            <Form.Item name="brand_id" label={text.brand}>
              <Select
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(brands)}
              />
            </Form.Item>
            <Form.Item name="application_ids" label={text.applications}>
              <Select
                mode="multiple"
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(applications)}
              />
            </Form.Item>
            <Form.Item name="lifecycle_id" label={text.lifecycle}>
              <Select
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(lifecycles)}
              />
            </Form.Item>
            <Form.Item
              name="category_id"
              label={text.category}
              rules={[{ required: true }]}
            >
              <Select
                showSearch
                optionFilterProp="label"
                options={categoryOptions}
              />
            </Form.Item>
            <Form.Item name="package_form_factor" label={text.package}>
              <Input />
            </Form.Item>
            <Form.Item
              name="status"
              label={text.visibility}
              rules={[{ required: true }]}
            >
              <Select
                disabled
                options={[
                  { value: "hidden", label: text.hidden },
                  { value: "published", label: text.publishedStatus },
                ]}
              />
            </Form.Item>
            <Form.Item name="document_url" label={text.legacyURL}>
              <Input type="url" />
            </Form.Item>
          </div>
          <Form.Item name="description" label={text.description}>
            <Input.TextArea rows={3} />
          </Form.Item>
          <Form.Item name="features" label={text.features}>
            <Input.TextArea rows={3} />
          </Form.Item>
          <Form.Item name="specification" label={text.specification}>
            <Input.TextArea rows={3} />
          </Form.Item>
          <Button onClick={() => void previewUnsaved()}>{text.preview}</Button>
        </Form>
      </Modal>
      <ProductDataModal
        locale={locale}
        product={dataProduct}
        open={dataProduct !== undefined}
        onClose={() => setDataProduct(undefined)}
        onChanged={load}
        onError={onError}
        onMessage={onMessage}
      />
      <ProductTranslationsModal
        product={translationProduct}
        settings={siteSettings}
        locale={locale}
        onClose={() => setTranslationProduct(undefined)}
        onError={onError}
        onSaved={() => void load()}
      />
    </Space>
  );
}
