import { useEffect, useMemo, useState } from "react";
import {
  Alert,
  Button,
  Card,
  Checkbox,
  Form,
  Input,
  Modal,
  Popconfirm,
  Select,
  Space,
  Table,
  Tag,
  Typography,
} from "antd";
import { api, downloadFile, postJSON, putJSON } from "./api";
import { ProductDataModal } from "./ProductDataModal";
import { ProductTranslationsModal } from "./ProductTranslationsModal";
import type {
  Category,
  DictionaryEntry,
  Product,
  ProductForm,
  SiteSettings,
} from "./types";

type Feedback = {
  onError: (error: unknown) => void;
  onMessage: (message: string) => void;
};
type CatalogLocale = "en-US" | "zh-TW";

const labels = {
  "en-US": {
    cloned: (source: string, created: string) =>
      `Cloned ${source} as ${created}. The clone is Hidden.`,
    saved: (part: string, revision: number) =>
      `Saved ${part} revision ${revision}.`,
    created: (part: string) => `Created ${part} as Hidden.`,
    mutated: (part: string, action: string) =>
      `${part} ${action === "hide" ? "hidden" : "archived"}.`,
    published: (part: string, revision: number) =>
      `${part} publication was queued at revision ${revision}.`,
    exportDownloaded: "Product export downloaded.",
    products: "Products",
    includeArchived: "Include archived",
    export: "Export XLSX",
    refresh: "Refresh",
    newProduct: "New product",
    partNumber: "Part number",
    name: "Name",
    manufacturer: "Manufacturer",
    category: "Category",
    state: "State",
    actions: "Actions",
    edit: "Edit",
    data: "Data",
    translations: "Translations",
    sourceLocale: "Source Locale",
    sourceLocaleHelp: "Defaults from the current Website Site Default, not your Admin UI language. You may override it for this Product.",
    clone: "Clone",
    publishConfirm: "Publish this product?",
    publishDescription:
      "The complete Product publication unit will become public after activation.",
    publish: "Publish",
    hideConfirm: "Hide this product from new public requests?",
    hide: "Hide",
    archiveConfirm: "Archive this product? Archived records are read-only.",
    archive: "Archive",
    editTitle: (part: string) => `Edit ${part}`,
    cloneTitle: (part: string) => `Clone ${part}`,
    save: "Save",
    createClone: "Create Hidden clone",
    createHidden: "Create Hidden product",
    publicTitle: "This Product is currently public",
    publicDescription:
      "Saving creates a new public revision. The current revision remains available until the complete replacement publication unit activates.",
    cloneInfo: "Create an independent Hidden clone",
    cloneDescription:
      "Enter a new Part Number. Product data and valid asset, image, document, specification, and application references are copied from the source.",
    slug: "URL slug",
    slugEdit: "Changing this changes the public URL.",
    slugCreate: "Leave blank to generate a stable suggestion once.",
    autoGenerated: "auto-generated",
    customPath: "Custom public path",
    customPathHelp:
      "Optional full internal path; it stays fixed when the global pattern changes.",
    customPathPlaceholder: "/featured/example",
    productName: "Product name",
    brand: "Brand",
    applications: "Applications",
    lifecycle: "Lifecycle",
    package: "Package / form factor",
    visibility: "Visibility",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "Legacy document URL",
    description: "Description",
    features: "Features",
    specification: "Specification",
    preview: "Preview unsaved changes",
    current: "current",
    archivedStatus: "archived",
  },
  "zh-TW": {
    cloned: (source: string, created: string) =>
      `已將 ${source} 複製為 ${created}；副本為 Hidden。`,
    saved: (part: string, revision: number) =>
      `已儲存 ${part} 修訂 ${revision}。`,
    created: (part: string) => `已建立 ${part}，狀態為 Hidden。`,
    mutated: (part: string, action: string) =>
      `${part} 已${action === "hide" ? "隱藏" : "封存"}。`,
    published: (part: string, revision: number) =>
      `${part} 的修訂 ${revision} 已排入發布。`,
    exportDownloaded: "產品匯出檔已下載。",
    products: "產品",
    includeArchived: "包含已封存",
    export: "匯出 XLSX",
    refresh: "重新整理",
    newProduct: "新增產品",
    partNumber: "料號",
    name: "名稱",
    manufacturer: "Manufacturer",
    category: "分類",
    state: "狀態",
    actions: "操作",
    edit: "編輯",
    data: "資料",
    translations: "翻譯",
    sourceLocale: "來源語系",
    sourceLocaleHelp: "預設取目前 Website Site Default，而不是你的 Admin UI 語系；此 Product 可單獨改選。",
    clone: "複製",
    publishConfirm: "要發布這項產品嗎？",
    publishDescription: "完整的 Product publication unit 啟用後才會公開。",
    publish: "發布",
    hideConfirm: "要停止核准這項產品的新公開請求嗎？",
    hide: "隱藏",
    archiveConfirm: "要封存這項產品嗎？封存後資料為唯讀。",
    archive: "封存",
    editTitle: (part: string) => `編輯 ${part}`,
    cloneTitle: (part: string) => `複製 ${part}`,
    save: "儲存",
    createClone: "建立 Hidden 副本",
    createHidden: "建立 Hidden 產品",
    publicTitle: "這項產品目前已公開",
    publicDescription:
      "儲存會建立新的公開修訂；目前修訂會保持可用，直到完整替代 publication unit 啟用。",
    cloneInfo: "建立獨立的 Hidden 副本",
    cloneDescription:
      "請輸入新料號。產品資料及有效的資產、圖片、文件、規格與應用參照會從來源複製。",
    slug: "URL slug",
    slugEdit: "變更後公開 URL 也會改變。",
    slugCreate: "留空時只會產生一次穩定建議。",
    autoGenerated: "自動產生",
    customPath: "自訂公開路徑",
    customPathHelp: "選填的完整內部路徑；全站 URL pattern 變更時仍保持固定。",
    customPathPlaceholder: "/featured/example",
    productName: "產品名稱",
    brand: "品牌",
    applications: "應用",
    lifecycle: "生命週期",
    package: "封裝／外型",
    visibility: "可見性",
    hidden: "Hidden",
    publishedStatus: "Published",
    legacyURL: "舊式文件 URL",
    description: "描述",
    features: "特色",
    specification: "規格",
    preview: "預覽未儲存變更",
    current: "目前",
    archivedStatus: "已封存",
  },
};

const blankProduct: ProductForm = {
  slug: "",
  custom_path: "",
  part_number: "",
  name: "",
  category_id: "cat_uncategorized",
  description: "",
  specification: "",
  document_url: "",
  status: "hidden",
};

export function CatalogPanel({
  locale,
  onError,
  onMessage,
}: Feedback & { locale: CatalogLocale }) {
  const text = labels[locale];
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [manufacturers, setManufacturers] = useState<DictionaryEntry[]>([]);
  const [brands, setBrands] = useState<DictionaryEntry[]>([]);
  const [applications, setApplications] = useState<DictionaryEntry[]>([]);
  const [lifecycles, setLifecycles] = useState<DictionaryEntry[]>([]);
  const [includeArchived, setIncludeArchived] = useState(false);
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [editing, setEditing] = useState<Product>();
  const [cloning, setCloning] = useState<Product>();
  const [dataProduct, setDataProduct] = useState<Product>();
  const [translationProduct, setTranslationProduct] = useState<Product>();
  const [siteSettings, setSiteSettings] = useState<SiteSettings>();
  const [formOpen, setFormOpen] = useState(false);
  const [form] = Form.useForm<ProductForm>();

  const exportProducts = async () => {
    setExporting(true);
    try {
      await downloadFile(
        "/admin/api/exports/products.xlsx",
        "prods-products.xlsx",
      );
      onMessage(text.exportDownloaded);
    } catch (error) {
      onError(error);
    } finally {
      setExporting(false);
    }
  };

  const load = async () => {
    setLoading(true);
    try {
      const [
        productRows,
        categoryRows,
        manufacturerRows,
        brandRows,
        applicationRows,
        lifecycleRows,
        settings,
      ] = await Promise.all([
        api<Product[]>(
          `/admin/api/products?include_archived=${includeArchived}`,
        ),
        api<Category[]>("/admin/api/categories"),
        api<DictionaryEntry[]>("/admin/api/dictionaries?kind=manufacturer"),
        api<DictionaryEntry[]>("/admin/api/dictionaries?kind=brand"),
        api<DictionaryEntry[]>("/admin/api/dictionaries?kind=application"),
        api<DictionaryEntry[]>("/admin/api/dictionaries?kind=lifecycle"),
        api<SiteSettings>("/admin/api/products/content-settings"),
      ]);
      setProducts(productRows ?? []);
      setCategories(categoryRows ?? []);
      setManufacturers(manufacturerRows ?? []);
      setBrands(brandRows ?? []);
      setApplications(applicationRows ?? []);
      setLifecycles(lifecycleRows ?? []);
      setSiteSettings(settings);
    } catch (error) {
      onError(error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [includeArchived]);

  const categoryOptions = useMemo(
    () =>
      categories
        .filter((item) => item.status === "active")
        .map((item) => ({ value: item.id, label: item.name })),
    [categories],
  );
  const dictionaryOptions = (rows: DictionaryEntry[]) =>
    rows
      .filter((item) => item.status === "active")
      .map((item) => ({ value: item.id, label: item.name }));

  const beginCreate = () => {
    setEditing(undefined);
    setCloning(undefined);
    form.setFieldsValue({ ...blankProduct, source_locale: siteSettings?.default_locale ?? "en-US" });
    setFormOpen(true);
  };

  const beginEdit = (product: Product) => {
    setEditing(product);
    setCloning(undefined);
    form.setFieldsValue({
      slug: product.slug,
      custom_path: product.custom_path,
      part_number: product.part_number,
      name: product.name,
      manufacturer_id: product.manufacturer_id,
      manufacturer: product.manufacturer,
      brand_id: product.brand_id,
      brand: product.brand,
      application_ids: product.application_ids ?? [],
      lifecycle_id: product.lifecycle_id,
      category_id: product.category_id,
      package_form_factor: product.package_form_factor,
      description: product.description,
      features: product.features,
      specification: product.specification,
      document_url: product.document_url,
      status: product.status,
    });
    setFormOpen(true);
  };

  const beginClone = (product: Product) => {
    setEditing(undefined);
    setCloning(product);
    form.setFieldsValue({
      slug: "",
      custom_path: "",
      part_number: "",
      name: product.name,
      manufacturer_id: product.manufacturer_id,
      manufacturer: product.manufacturer,
      brand_id: product.brand_id,
      brand: product.brand,
      application_ids: product.application_ids ?? [],
      lifecycle_id: product.lifecycle_id,
      category_id: product.category_id,
      package_form_factor: product.package_form_factor,
      description: product.description,
      features: product.features,
      specification: product.specification,
      document_url: product.document_url,
      status: "hidden",
    });
    setFormOpen(true);
  };

  const save = async (values: ProductForm) => {
    try {
      if (cloning) {
        const created = await postJSON<Product>(
          `/admin/api/products/${cloning.id}/clone`,
          {
            expected_revision: cloning.revision,
            product: { ...values, status: "hidden" },
          },
        );
        onMessage(text.cloned(cloning.part_number, created.part_number));
      } else if (editing) {
        let updated = await putJSON<Product>(
          `/admin/api/products/${editing.id}`,
          {
            expected_revision: editing.revision,
            product: { ...editing, ...values },
          },
        );
        if (
          values.slug !== editing.slug ||
          (values.custom_path ?? "") !== (editing.custom_path ?? "")
        ) {
          updated = await postJSON<Product>(
            `/admin/api/products/${editing.id}/url`,
            {
              expected_revision: updated.revision,
              slug: values.slug,
              custom_path: values.custom_path ?? "",
            },
          );
        }
        onMessage(text.saved(updated.part_number, updated.revision));
      } else {
      const created = await postJSON<Product>("/admin/api/products", values);
        onMessage(text.created(created.part_number));
      }
      setEditing(undefined);
      setCloning(undefined);
      setFormOpen(false);
      form.resetFields();
      await load();
    } catch (error) {
      onError(error);
      await load();
    }
  };

  const previewUnsaved = async () => {
    let previewWindow: Window | null = null;
    try {
      const values = await form.validateFields();
      previewWindow = window.open("about:blank", "_blank");
      const receipt = await postJSON<{ url: string }>(
        "/admin/api/previews/products",
        {
          expected_revision: editing?.revision ?? 0,
          product: editing ? { ...editing, ...values } : values,
        },
      );
      if (previewWindow) {
        previewWindow.location.assign(receipt.url);
      } else {
        window.open(receipt.url, "_blank", "noopener,noreferrer");
      }
    } catch (error) {
      previewWindow?.close();
      onError(error);
    }
  };

  const mutate = async (product: Product, action: "hide" | "archive") => {
    try {
      await postJSON<void>(`/admin/api/products/${product.id}/${action}`, {
        expected_revision: product.revision,
      });
      onMessage(text.mutated(product.part_number, action));
      await load();
    } catch (error) {
      onError(error);
      await load();
    }
  };

  const publish = async (product: Product) => {
    try {
      const updated = await putJSON<Product>(
        `/admin/api/products/${product.id}`,
        {
          expected_revision: product.revision,
          product: { ...product, status: "published" },
        },
      );
      onMessage(text.published(updated.part_number, updated.revision));
      await load();
    } catch (error) {
      onError(error);
      await load();
    }
  };

  return (
    <Space direction="vertical" size="large" className="panel-stack">
      <Card
        title={text.products}
        extra={
          <Space wrap>
            <Checkbox
              checked={includeArchived}
              onChange={(event) => setIncludeArchived(event.target.checked)}
            >
              {text.includeArchived}
            </Checkbox>
            <Button loading={exporting} onClick={() => void exportProducts()}>
              {text.export}
            </Button>
            <Button onClick={() => void load()}>{text.refresh}</Button>
            <Button type="primary" onClick={beginCreate}>
              {text.newProduct}
            </Button>
          </Space>
        }
      >
        <Table<Product>
          rowKey="id"
          loading={loading}
          dataSource={products}
          pagination={{ pageSize: 20, hideOnSinglePage: true }}
          scroll={{ x: 880 }}
          columns={[
            {
              title: text.partNumber,
              dataIndex: "part_number",
              sorter: (a, b) => a.part_number.localeCompare(b.part_number),
            },
            {
              title: text.name,
              dataIndex: "name",
              render: (value: string) =>
                value || <Typography.Text type="secondary">—</Typography.Text>,
            },
            {
              title: text.manufacturer,
              render: (_, row) =>
                row.manufacturer || row.manufacturer_id || "—",
            },
            {
              title: text.category,
              render: (_, row) =>
                categories.find((item) => item.id === row.category_id)?.name ??
                row.category_id,
            },
            {
              title: text.state,
              render: (_, row) => (
                <Space>
                  <Tag
                    color={row.record_state === "archived" ? "default" : "blue"}
                  >
                    {row.record_state === "archived"
                      ? text.archivedStatus
                      : text.current}
                  </Tag>
                  <Tag color={row.status === "published" ? "green" : "gold"}>
                    {row.status === "published"
                      ? text.publishedStatus
                      : text.hidden}
                  </Tag>
                  <Typography.Text type="secondary">
                    r{row.revision}
                  </Typography.Text>
                </Space>
              ),
            },
            {
              title: text.actions,
              fixed: "right",
              render: (_, row) => (
                <Space>
                  <Button
                    size="small"
                    disabled={row.record_state === "archived"}
                    onClick={() => beginEdit(row)}
                  >
                    {text.edit}
                  </Button>
                  <Button
                    size="small"
                    disabled={row.record_state === "archived"}
                    onClick={() => setDataProduct(row)}
                  >
                    {text.data}
                  </Button>
                  {siteSettings?.content_multilingual_enabled && (
                    <Button
                      size="small"
                      disabled={row.record_state === "archived"}
                      onClick={() => setTranslationProduct(row)}
                    >
                      {text.translations}
                    </Button>
                  )}
                  <Button size="small" onClick={() => beginClone(row)}>
                    {text.clone}
                  </Button>
                  {row.record_state !== "archived" &&
                    row.status === "hidden" && (
                      <Popconfirm
                        title={text.publishConfirm}
                        description={text.publishDescription}
                        onConfirm={() => void publish(row)}
                      >
                        <Button size="small" type="primary">
                          {text.publish}
                        </Button>
                      </Popconfirm>
                    )}
                  {row.record_state !== "archived" &&
                    row.status === "published" && (
                      <Popconfirm
                        title={text.hideConfirm}
                        onConfirm={() => void mutate(row, "hide")}
                      >
                        <Button size="small">{text.hide}</Button>
                      </Popconfirm>
                    )}
                  {row.record_state !== "archived" && (
                    <Popconfirm
                      title={text.archiveConfirm}
                      onConfirm={() => void mutate(row, "archive")}
                    >
                      <Button size="small" danger>
                        {text.archive}
                      </Button>
                    </Popconfirm>
                  )}
                </Space>
              ),
            },
          ]}
        />
      </Card>

      <Modal
        open={formOpen}
        title={
          editing
            ? text.editTitle(editing.part_number)
            : cloning
              ? text.cloneTitle(cloning.part_number)
              : text.newProduct
        }
        okText={
          editing ? text.save : cloning ? text.createClone : text.createHidden
        }
        onOk={() => form.submit()}
        onCancel={() => {
          setEditing(undefined);
          setCloning(undefined);
          setFormOpen(false);
          form.resetFields();
        }}
        width={760}
        destroyOnHidden
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={(values) => void save(values)}
          initialValues={blankProduct}
        >
          {editing?.status === "published" ? (
            <Alert
              className="bottom-gap"
              type="warning"
              showIcon
              message={text.publicTitle}
              description={text.publicDescription}
            />
          ) : null}
          {cloning ? (
            <Alert
              className="bottom-gap"
              type="info"
              showIcon
              message={text.cloneInfo}
              description={text.cloneDescription}
            />
          ) : null}
          <div className="form-grid">
            <Form.Item
              name="part_number"
              label={text.partNumber}
              rules={[{ required: true }]}
            >
              <Input />
            </Form.Item>
            <Form.Item
              name="slug"
              label={text.slug}
              extra={editing ? text.slugEdit : text.slugCreate}
            >
              <Input placeholder={text.autoGenerated} />
            </Form.Item>
            <Form.Item
              name="custom_path"
              label={text.customPath}
              extra={text.customPathHelp}
            >
              <Input placeholder={text.customPathPlaceholder} />
            </Form.Item>
            <Form.Item name="name" label={text.productName}>
              <Input />
            </Form.Item>
            {!editing && !cloning ? (
              <Form.Item name="source_locale" label={text.sourceLocale} extra={text.sourceLocaleHelp} rules={[{ required: true }]}>
                <Select options={(siteSettings?.supported_locales ?? []).map((value) => ({ value, label: value }))} />
              </Form.Item>
            ) : null}
            <Form.Item name="manufacturer_id" label={text.manufacturer}>
              <Select
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(manufacturers)}
              />
            </Form.Item>
            <Form.Item name="brand_id" label={text.brand}>
              <Select
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(brands)}
              />
            </Form.Item>
            <Form.Item name="application_ids" label={text.applications}>
              <Select
                mode="multiple"
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(applications)}
              />
            </Form.Item>
            <Form.Item name="lifecycle_id" label={text.lifecycle}>
              <Select
                allowClear
                showSearch
                optionFilterProp="label"
                options={dictionaryOptions(lifecycles)}
              />
            </Form.Item>
            <Form.Item
              name="category_id"
              label={text.category}
              rules={[{ required: true }]}
            >
              <Select
                showSearch
                optionFilterProp="label"
                options={categoryOptions}
              />
            </Form.Item>
            <Form.Item name="package_form_factor" label={text.package}>
              <Input />
            </Form.Item>
            <Form.Item
              name="status"
              label={text.visibility}
              rules={[{ required: true }]}
            >
              <Select
                disabled={Boolean(cloning) || editing?.status === "published"}
                options={[
                  { value: "hidden", label: text.hidden },
                  { value: "published", label: text.publishedStatus },
                ]}
              />
            </Form.Item>
            <Form.Item name="document_url" label={text.legacyURL}>
              <Input type="url" />
            </Form.Item>
          </div>
          <Form.Item name="description" label={text.description}>
            <Input.TextArea rows={3} />
          </Form.Item>
          <Form.Item name="features" label={text.features}>
            <Input.TextArea rows={3} />
          </Form.Item>
          <Form.Item name="specification" label={text.specification}>
            <Input.TextArea rows={3} />
          </Form.Item>
          <Button onClick={() => void previewUnsaved()}>{text.preview}</Button>
        </Form>
      </Modal>
      <ProductDataModal
        locale={locale}
        product={dataProduct}
        open={dataProduct !== undefined}
        onClose={() => setDataProduct(undefined)}
        onChanged={load}
        onError={onError}
        onMessage={onMessage}
      />
      <ProductTranslationsModal
        product={translationProduct}
        settings={siteSettings}
        locale={locale}
        onClose={() => setTranslationProduct(undefined)}
        onError={onError}
        onSaved={() => void load()}
      />
    </Space>
  );
}
