import deDE from "antd/locale/de_DE";
import enUS from "antd/locale/en_US";
import esES from "antd/locale/es_ES";
import frFR from "antd/locale/fr_FR";
import itIT from "antd/locale/it_IT";
import jaJP from "antd/locale/ja_JP";
import koKR from "antd/locale/ko_KR";
import ptBR from "antd/locale/pt_BR";
import zhCN from "antd/locale/zh_CN";
import zhTW from "antd/locale/zh_TW";

export const systemLocaleCodes = ["en-US", "zh-TW", "zh-CN", "ja-JP", "ko-KR", "de-DE", "fr-FR", "it-IT", "es-ES", "pt-BR"] as const;
export type SystemLocale = (typeof systemLocaleCodes)[number];

export const systemLocaleOptions = [
  { value: "en-US", label: "English (United States)" },
  { value: "zh-TW", label: "繁體中文" },
  { value: "zh-CN", label: "简体中文" },
  { value: "ja-JP", label: "日本語" },
  { value: "ko-KR", label: "한국어" },
  { value: "de-DE", label: "Deutsch" },
  { value: "fr-FR", label: "Français" },
  { value: "it-IT", label: "Italiano" },
  { value: "es-ES", label: "Español" },
  { value: "pt-BR", label: "Português (Brasil)" },
] satisfies Array<{ value: SystemLocale; label: string }>;

export const antdLocale = { "en-US": enUS, "zh-TW": zhTW, "zh-CN": zhCN, "ja-JP": jaJP, "ko-KR": koKR, "de-DE": deDE, "fr-FR": frFR, "it-IT": itIT, "es-ES": esES, "pt-BR": ptBR };

type Copy = {
  common: { language: string; loading: string; requestFailed: string; retry: string; setup: string; recovery: string; maintenance: string };
  installer: { title: string; claim: string; claimHelp: string; token: string; claimed: string; setup: string; email: string; name: string; password: string; confirm: string; passwordHelp: string; defaultLocale: string; supportedLocales: string; localesHelp: string; timeZone: string; finish: string; complete: string };
  recovery: { title: string; blocked: string; sensitive: string; sensitiveHelp: string; failed: string; disabled: string; none: string; diagnostic: string; points: string; confirm: string; understood: string; popTitle: string; popHelp: string; restore: string; complete: string; restart: string; schema: string };
  maintenance: { unavailable: string; fallback: string; retry: string; restored: string; restoredHelp: string; catalog: string };
};

export const extraSystemCopy: Record<Exclude<SystemLocale, "en-US" | "zh-TW">, Copy> = {
  "zh-CN": {
    common: { language: "界面语言", loading: "正在加载系统状态…", requestFailed: "请求失败", retry: "重试", setup: "系统安装", recovery: "系统恢复", maintenance: "系统维护" },
    installer: { title: "设置 Prods", claim: "认领此安装程序", claimHelp: "输入 Prods 在此主机终端显示的一次性 bootstrap token。", token: "Bootstrap token", claimed: "此安装程序已由另一个浏览器认领。请返回原浏览器，或重启 Prods 获取新 token。", setup: "创建第一位 Owner 和最低限度站点设置。产品、网站、SMTP 和公开 URL 可稍后配置。", email: "Owner 电子邮箱", name: "Owner 显示名称", password: "密码", confirm: "确认密码", passwordHelp: "至少 8 个字符，并至少包含一个字母和一个数字。", defaultLocale: "默认语言", supportedLocales: "支持的语言", localesHelp: "选择此 binary 内含的一种或多种界面语言，且必须包含默认语言。", timeZone: "站点时区", finish: "完成安装", complete: "安装数据已原子保存。请重启 Prods 进入正常模式。" },
    recovery: { title: "需要系统恢复", blocked: "现有站点无法进入正常模式。", sensitive: "恢复点包含敏感数据。", sensitiveHelp: "恢复可能带回所选时间点后已删除的 RFQ 个人数据；已发送的邮件无法撤回。", failed: "系统恢复未完成", disabled: "恢复控制记录不明确，目前禁止恢复。", none: "未找到可读且已验证的恢复点。", diagnostic: "诊断信息", points: "已验证恢复点", confirm: "输入 RESTORE 以确认", understood: "我了解这是固定顺序的恢复操作。", popTitle: "恢复所选的已验证恢复点？", popHelp: "durable journal 进入 prepared 后只能向前完成。", restore: "恢复所选时间点", complete: "恢复完成并通过验证", restart: "请正常重启 Prods；恢复会话已关闭。", schema: "schema" },
    maintenance: { unavailable: "站点正在维护", fallback: "Prods 正在完成受控维护操作。", retry: "重新检查", restored: "正常服务已恢复", restoredHelp: "维护模式已结束。", catalog: "打开产品目录" },
  },
  "ja-JP": {
    common: { language: "表示言語", loading: "システム状態を読み込み中…", requestFailed: "リクエストに失敗しました", retry: "再試行", setup: "セットアップ", recovery: "復旧", maintenance: "システムメンテナンス" },
    installer: { title: "Prods のセットアップ", claim: "インストーラーを引き継ぐ", claimHelp: "このホストの Prods 端末に表示された一回限りの bootstrap token を入力してください。", token: "Bootstrap token", claimed: "別のブラウザーがこのインストーラーを使用中です。元のブラウザーに戻るか、Prods を再起動して新しい token を取得してください。", setup: "最初の Owner と最小限のサイト設定を作成します。製品、Website、SMTP、公開 URL は後で設定できます。", email: "Owner のメール", name: "Owner の表示名", password: "パスワード", confirm: "パスワード確認", passwordHelp: "8 文字以上で、英字と数字を 1 文字以上含めてください。", defaultLocale: "既定の言語", supportedLocales: "対応言語", localesHelp: "binary に含まれる言語を 1 つ以上選び、既定の言語を含めてください。", timeZone: "サイトのタイムゾーン", finish: "インストールを完了", complete: "設定は原子的に保存されました。Prods を再起動して通常モードに入ってください。" },
    recovery: { title: "システムの復旧が必要です", blocked: "現在のサイトは通常モードで開始できません。", sensitive: "復元ポイントには機密データが含まれます。", sensitiveHelp: "復元すると、その後削除された RFQ 個人データが戻る場合があります。送信済みメールは取り消せません。", failed: "復旧が完了しませんでした", disabled: "復旧制御記録が不明確なため復元できません。", none: "読み取り可能で検証済みの復元ポイントがありません。", diagnostic: "診断", points: "検証済み復元ポイント", confirm: "RESTORE と入力して確認", understood: "固定順序で復元されることを理解しました。", popTitle: "選択した復元ポイントに戻しますか？", popHelp: "journal が prepared になると復旧は前進のみです。", restore: "選択したポイントを復元", complete: "復元と検証が完了しました", restart: "Prods を通常どおり再起動してください。復旧セッションは終了しました。", schema: "スキーマ" },
    maintenance: { unavailable: "サイトはメンテナンス中です", fallback: "Prods は制御されたメンテナンス処理を完了しています。", retry: "再確認", restored: "通常サービスに戻りました", restoredHelp: "メンテナンスモードは終了しました。", catalog: "製品カタログを開く" },
  },
  "ko-KR": {
    common: { language: "인터페이스 언어", loading: "시스템 상태를 불러오는 중…", requestFailed: "요청 실패", retry: "다시 시도", setup: "설치", recovery: "복구", maintenance: "시스템 유지보수" },
    installer: { title: "Prods 설정", claim: "설치 프로그램 인계", claimHelp: "이 호스트의 Prods 터미널에 표시된 일회용 bootstrap token을 입력하세요.", token: "Bootstrap token", claimed: "다른 브라우저가 이 설치 프로그램을 사용 중입니다. 원래 브라우저로 돌아가거나 Prods를 다시 시작해 새 token을 받으세요.", setup: "첫 Owner와 최소 사이트 설정을 만듭니다. 제품, Website, SMTP, 공개 URL은 나중에 설정할 수 있습니다.", email: "Owner 이메일", name: "Owner 표시 이름", password: "비밀번호", confirm: "비밀번호 확인", passwordHelp: "8자 이상이며 문자와 숫자를 각각 하나 이상 포함하세요.", defaultLocale: "기본 언어", supportedLocales: "지원 언어", localesHelp: "binary에 포함된 언어를 하나 이상 선택하고 기본 언어를 포함하세요.", timeZone: "사이트 시간대", finish: "설치 완료", complete: "설정이 원자적으로 저장되었습니다. Prods를 다시 시작해 정상 모드로 진입하세요." },
    recovery: { title: "시스템 복구 필요", blocked: "현재 사이트를 정상 모드로 시작할 수 없습니다.", sensitive: "복원 지점에 민감한 데이터가 포함됩니다.", sensitiveHelp: "복원 후 삭제된 RFQ 개인정보가 다시 나타날 수 있으며 이미 보낸 이메일은 취소할 수 없습니다.", failed: "복구가 완료되지 않음", disabled: "복구 제어 기록이 불명확하여 복원이 비활성화되었습니다.", none: "읽을 수 있고 검증된 복원 지점이 없습니다.", diagnostic: "진단", points: "검증된 복원 지점", confirm: "확인하려면 RESTORE 입력", understood: "고정 순서 복원 작업임을 이해합니다.", popTitle: "선택한 검증 지점을 복원할까요?", popHelp: "journal이 prepared 상태가 되면 앞으로만 진행됩니다.", restore: "선택 지점 복원", complete: "복원 및 검증 완료", restart: "Prods를 정상적으로 다시 시작하세요. 복구 세션이 종료되었습니다.", schema: "스키마" },
    maintenance: { unavailable: "사이트 유지보수 중", fallback: "Prods가 제어된 유지보수 작업을 완료하는 중입니다.", retry: "다시 확인", restored: "정상 서비스 복구됨", restoredHelp: "유지보수 모드가 종료되었습니다.", catalog: "제품 카탈로그 열기" },
  },
  "de-DE": {
    common: { language: "Oberflächensprache", loading: "Systemstatus wird geladen…", requestFailed: "Anfrage fehlgeschlagen", retry: "Erneut versuchen", setup: "Einrichtung", recovery: "Wiederherstellung", maintenance: "Systemwartung" },
    installer: { title: "Prods einrichten", claim: "Installation übernehmen", claimHelp: "Geben Sie das einmalige bootstrap token aus dem Prods-Terminal dieses Hosts ein.", token: "Bootstrap token", claimed: "Diese Installation wird bereits in einem anderen Browser verwendet. Kehren Sie dorthin zurück oder starten Sie Prods für ein neues token neu.", setup: "Erstellt den ersten Owner und minimale Site-Einstellungen. Produkte, Website, SMTP und öffentliche URL können später konfiguriert werden.", email: "Owner-E-Mail", name: "Owner-Anzeigename", password: "Passwort", confirm: "Passwort bestätigen", passwordHelp: "Mindestens 8 Zeichen mit mindestens einem Buchstaben und einer Ziffer.", defaultLocale: "Standardsprache", supportedLocales: "Unterstützte Sprachen", localesHelp: "Wählen Sie mindestens eine im binary enthaltene Sprache und schließen Sie die Standardsprache ein.", timeZone: "Site-Zeitzone", finish: "Installation abschließen", complete: "Die Installation wurde atomar gespeichert. Starten Sie Prods für den Normalbetrieb neu." },
    recovery: { title: "Systemwiederherstellung erforderlich", blocked: "Die bestehende Site kann nicht normal gestartet werden.", sensitive: "Wiederherstellungspunkte enthalten sensible Daten.", sensitiveHelp: "Eine Wiederherstellung kann später gelöschte RFQ-Personendaten zurückbringen; gesendete E-Mails sind nicht rückrufbar.", failed: "Wiederherstellung nicht abgeschlossen", disabled: "Wiederherstellung ist wegen mehrdeutiger Steuerdaten deaktiviert.", none: "Kein lesbarer, verifizierter Wiederherstellungspunkt gefunden.", diagnostic: "Diagnose", points: "Verifizierte Wiederherstellungspunkte", confirm: "Zur Bestätigung RESTORE eingeben", understood: "Ich verstehe die Wiederherstellung in fester Reihenfolge.", popTitle: "Gewählten verifizierten Punkt wiederherstellen?", popHelp: "Nach prepared kann das Journal nur vorwärts fortgesetzt werden.", restore: "Gewählten Punkt wiederherstellen", complete: "Wiederherstellung abgeschlossen und geprüft", restart: "Starten Sie Prods normal neu. Die Sitzung ist geschlossen.", schema: "Schema" },
    maintenance: { unavailable: "Site wird gewartet", fallback: "Prods schließt einen kontrollierten Wartungsvorgang ab.", retry: "Erneut prüfen", restored: "Normalbetrieb wiederhergestellt", restoredHelp: "Der Wartungsmodus ist beendet.", catalog: "Produktkatalog öffnen" },
  },
  "fr-FR": {
    common: { language: "Langue de l’interface", loading: "Chargement de l’état du système…", requestFailed: "Échec de la requête", retry: "Réessayer", setup: "Installation", recovery: "Récupération", maintenance: "Maintenance système" },
    installer: { title: "Configurer Prods", claim: "Prendre en charge l’installation", claimHelp: "Saisissez le bootstrap token à usage unique affiché dans le terminal Prods de cet hôte.", token: "Bootstrap token", claimed: "Cette installation est déjà utilisée dans un autre navigateur. Revenez-y ou redémarrez Prods pour obtenir un nouveau token.", setup: "Crée le premier Owner et les réglages minimaux du site. Produits, Website, SMTP et URL publique pourront être configurés plus tard.", email: "E-mail du Owner", name: "Nom affiché du Owner", password: "Mot de passe", confirm: "Confirmer le mot de passe", passwordHelp: "Au moins 8 caractères, dont une lettre et un chiffre.", defaultLocale: "Langue par défaut", supportedLocales: "Langues prises en charge", localesHelp: "Choisissez au moins une langue incluse dans le binary et incluez la langue par défaut.", timeZone: "Fuseau horaire du site", finish: "Terminer l’installation", complete: "L’installation a été enregistrée de façon atomique. Redémarrez Prods en mode normal." },
    recovery: { title: "Récupération système requise", blocked: "Le site existant ne peut pas démarrer normalement.", sensitive: "Les points de restauration contiennent des données sensibles.", sensitiveHelp: "Une restauration peut rétablir des données RFQ supprimées depuis ; les e-mails envoyés ne peuvent pas être rappelés.", failed: "Récupération non terminée", disabled: "La restauration est désactivée car les données de contrôle sont ambiguës.", none: "Aucun point lisible et vérifié n’a été trouvé.", diagnostic: "Diagnostic", points: "Points de restauration vérifiés", confirm: "Saisissez RESTORE pour confirmer", understood: "Je comprends l’opération de restauration à ordre fixe.", popTitle: "Restaurer le point vérifié sélectionné ?", popHelp: "Après prepared, le journal ne peut qu’avancer.", restore: "Restaurer le point sélectionné", complete: "Restauration terminée et vérifiée", restart: "Redémarrez Prods normalement. La session est fermée.", schema: "schéma" },
    maintenance: { unavailable: "Site en maintenance", fallback: "Prods termine une opération de maintenance contrôlée.", retry: "Vérifier à nouveau", restored: "Service normal rétabli", restoredHelp: "Le mode maintenance est terminé.", catalog: "Ouvrir le catalogue" },
  },
  "it-IT": {
    common: { language: "Lingua dell’interfaccia", loading: "Caricamento stato del sistema…", requestFailed: "Richiesta non riuscita", retry: "Riprova", setup: "Installazione", recovery: "Ripristino", maintenance: "Manutenzione del sistema" },
    installer: { title: "Configura Prods", claim: "Prendi in carico l’installazione", claimHelp: "Inserisci il bootstrap token monouso mostrato nel terminale Prods di questo host.", token: "Bootstrap token", claimed: "Questa installazione è già in uso in un altro browser. Torna lì o riavvia Prods per un nuovo token.", setup: "Crea il primo Owner e le impostazioni minime del sito. Prodotti, Website, SMTP e URL pubblico si configurano in seguito.", email: "E-mail Owner", name: "Nome visualizzato Owner", password: "Password", confirm: "Conferma password", passwordHelp: "Almeno 8 caratteri con una lettera e un numero.", defaultLocale: "Lingua predefinita", supportedLocales: "Lingue supportate", localesHelp: "Scegli almeno una lingua inclusa nel binary e includi quella predefinita.", timeZone: "Fuso orario del sito", finish: "Completa installazione", complete: "Installazione salvata atomicamente. Riavvia Prods in modalità normale." },
    recovery: { title: "Ripristino del sistema richiesto", blocked: "Il sito esistente non può avviarsi normalmente.", sensitive: "I punti di ripristino contengono dati sensibili.", sensitiveHelp: "Il ripristino può recuperare dati RFQ poi eliminati; le e-mail inviate non possono essere richiamate.", failed: "Ripristino non completato", disabled: "Ripristino disabilitato perché i dati di controllo sono ambigui.", none: "Nessun punto leggibile e verificato trovato.", diagnostic: "Diagnostica", points: "Punti verificati", confirm: "Digita RESTORE per confermare", understood: "Comprendo il ripristino in ordine fisso.", popTitle: "Ripristinare il punto verificato selezionato?", popHelp: "Dopo prepared il journal può solo avanzare.", restore: "Ripristina punto selezionato", complete: "Ripristino completato e verificato", restart: "Riavvia Prods normalmente. La sessione è chiusa.", schema: "schema" },
    maintenance: { unavailable: "Sito in manutenzione", fallback: "Prods sta completando un’operazione di manutenzione controllata.", retry: "Controlla di nuovo", restored: "Servizio normale ripristinato", restoredHelp: "La modalità manutenzione è terminata.", catalog: "Apri catalogo prodotti" },
  },
  "es-ES": {
    common: { language: "Idioma de la interfaz", loading: "Cargando estado del sistema…", requestFailed: "Error en la solicitud", retry: "Reintentar", setup: "Instalación", recovery: "Recuperación", maintenance: "Mantenimiento del sistema" },
    installer: { title: "Configurar Prods", claim: "Tomar control de la instalación", claimHelp: "Introduce el bootstrap token de un solo uso mostrado en el terminal Prods de este host.", token: "Bootstrap token", claimed: "Otro navegador ya controla esta instalación. Vuelve a él o reinicia Prods para obtener un token nuevo.", setup: "Crea el primer Owner y la configuración mínima. Productos, Website, SMTP y URL pública se configuran después.", email: "Correo del Owner", name: "Nombre visible del Owner", password: "Contraseña", confirm: "Confirmar contraseña", passwordHelp: "Al menos 8 caracteres con una letra y un número.", defaultLocale: "Idioma predeterminado", supportedLocales: "Idiomas compatibles", localesHelp: "Elige al menos un idioma incluido en el binary e incluye el predeterminado.", timeZone: "Zona horaria del sitio", finish: "Completar instalación", complete: "La instalación se guardó atómicamente. Reinicia Prods en modo normal." },
    recovery: { title: "Se requiere recuperación del sistema", blocked: "El sitio actual no puede iniciarse normalmente.", sensitive: "Los puntos de restauración contienen datos sensibles.", sensitiveHelp: "Restaurar puede recuperar datos personales de RFQ eliminados después; los correos enviados no pueden retirarse.", failed: "La recuperación no terminó", disabled: "La restauración está desactivada por datos de control ambiguos.", none: "No se encontró un punto legible y verificado.", diagnostic: "Diagnóstico", points: "Puntos verificados", confirm: "Escribe RESTORE para confirmar", understood: "Entiendo la restauración en orden fijo.", popTitle: "¿Restaurar el punto verificado seleccionado?", popHelp: "Después de prepared, el journal solo puede avanzar.", restore: "Restaurar punto seleccionado", complete: "Restauración completada y verificada", restart: "Reinicia Prods normalmente. La sesión se cerró.", schema: "esquema" },
    maintenance: { unavailable: "Sitio en mantenimiento", fallback: "Prods está completando una operación de mantenimiento controlada.", retry: "Comprobar de nuevo", restored: "Servicio normal restablecido", restoredHelp: "El modo de mantenimiento terminó.", catalog: "Abrir catálogo" },
  },
  "pt-BR": {
    common: { language: "Idioma da interface", loading: "Carregando estado do sistema…", requestFailed: "Falha na solicitação", retry: "Tentar novamente", setup: "Instalação", recovery: "Recuperação", maintenance: "Manutenção do sistema" },
    installer: { title: "Configurar o Prods", claim: "Assumir a instalação", claimHelp: "Digite o bootstrap token de uso único mostrado no terminal do Prods neste host.", token: "Bootstrap token", claimed: "Outro navegador já assumiu esta instalação. Volte a ele ou reinicie o Prods para obter um novo token.", setup: "Cria o primeiro Owner e as configurações mínimas. Produtos, Website, SMTP e URL pública podem ser configurados depois.", email: "E-mail do Owner", name: "Nome de exibição do Owner", password: "Senha", confirm: "Confirmar senha", passwordHelp: "Use pelo menos 8 caracteres, incluindo uma letra e um número.", defaultLocale: "Idioma padrão", supportedLocales: "Idiomas compatíveis", localesHelp: "Escolha pelo menos um idioma incluído no binary e inclua o idioma padrão.", timeZone: "Fuso horário do site", finish: "Concluir instalação", complete: "A instalação foi salva atomicamente. Reinicie o Prods no modo normal." },
    recovery: { title: "Recuperação do sistema necessária", blocked: "O site existente não pode iniciar normalmente.", sensitive: "Os pontos de restauração contêm dados sensíveis.", sensitiveHelp: "A restauração pode recuperar dados pessoais de RFQ removidos depois; e-mails enviados não podem ser cancelados.", failed: "A recuperação não foi concluída", disabled: "A restauração está desativada porque os dados de controle são ambíguos.", none: "Nenhum ponto legível e verificado foi encontrado.", diagnostic: "Diagnóstico", points: "Pontos verificados", confirm: "Digite RESTORE para confirmar", understood: "Entendo a restauração em ordem fixa.", popTitle: "Restaurar o ponto verificado selecionado?", popHelp: "Após prepared, o journal só pode avançar.", restore: "Restaurar ponto selecionado", complete: "Restauração concluída e verificada", restart: "Reinicie o Prods normalmente. A sessão foi encerrada.", schema: "schema" },
    maintenance: { unavailable: "Site em manutenção", fallback: "O Prods está concluindo uma operação de manutenção controlada.", retry: "Verificar novamente", restored: "Serviço normal restaurado", restoredHelp: "O modo de manutenção terminou.", catalog: "Abrir catálogo de produtos" },
  },
};

export const extraCommonText = Object.fromEntries(Object.entries(extraSystemCopy).map(([locale, copy]) => [locale, copy.common]));
export const extraInstallerText = Object.fromEntries(Object.entries(extraSystemCopy).map(([locale, copy]) => [locale, copy.installer]));
export const extraRecoveryText = Object.fromEntries(Object.entries(extraSystemCopy).map(([locale, copy]) => [locale, copy.recovery]));
export const extraMaintenanceText = Object.fromEntries(Object.entries(extraSystemCopy).map(([locale, copy]) => [locale, copy.maintenance]));
