package referencecatalog

import (
	"slices"
	"strings"

	"prods/internal/catalog"
)

type Manifest struct {
	DatasetVersion      string                `json:"dataset_version"`
	Seed                int64                 `json:"seed"`
	ReferenceTime       string                `json:"reference_time"`
	SourceStatement     string                `json:"source_statement"`
	PublicationApplied  bool                  `json:"publication_applied"`
	Summary             ManifestSummary       `json:"summary"`
	Taxonomy            []TaxonomyExpectation `json:"taxonomy"`
	ContentDistribution map[string]int        `json:"content_distribution"`
	LocaleDistribution  map[string]int        `json:"locale_distribution"`
	PublishedProductIDs []string              `json:"published_product_ids"`
	HiddenProductIDs    []string              `json:"hidden_product_ids"`
	ArchivedProductIDs  []string              `json:"archived_product_ids"`
	CommonScopes        []CommonExpectation   `json:"common_scopes"`
	Queries             []QueryExpectation    `json:"queries"`
	Assets              []AssetExpectation    `json:"assets"`
}

type ManifestSummary struct {
	BusinessTopCategories     int `json:"business_top_categories"`
	CategoriesIncludingSystem int `json:"categories_including_system"`
	SpecSets                  int `json:"spec_sets"`
	Specs                     int `json:"specs"`
	Products                  int `json:"products"`
	Manufacturers             int `json:"manufacturers"`
	Brands                    int `json:"brands"`
	Applications              int `json:"applications"`
	Published                 int `json:"published"`
	Hidden                    int `json:"hidden"`
	Archived                  int `json:"archived"`
}

type TaxonomyExpectation struct {
	ID            string `json:"id"`
	ParentID      string `json:"parent_id,omitempty"`
	Path          string `json:"path"`
	SpecSetID     string `json:"spec_set_id,omitempty"`
	DirectPublic  int    `json:"direct_public"`
	SubtreePublic int    `json:"subtree_public"`
}

type CommonExpectation struct {
	Name        string   `json:"name"`
	CategoryIDs []string `json:"category_ids"`
	ProductIDs  []string `json:"product_ids"`
	SpecIDs     []string `json:"common_spec_ids"`
}

type QueryExpectation struct {
	Name       string   `json:"name"`
	Query      string   `json:"query"`
	Count      int      `json:"count"`
	ProductIDs []string `json:"product_ids"`
}

type AssetExpectation struct {
	Kind   string `json:"kind"`
	Path   string `json:"path,omitempty"`
	Source string `json:"source"`
	Usage  string `json:"usage"`
}

func buildManifest(dataset Dataset) Manifest {
	manifest := Manifest{
		DatasetVersion:      dataset.Version,
		Seed:                dataset.Seed,
		ReferenceTime:       dataset.ReferenceTime.Format("2006-01-02T15:04:05Z"),
		SourceStatement:     SourceStatement,
		ContentDistribution: map[string]int{},
		LocaleDistribution:  map[string]int{"en-US": len(dataset.Products)},
		PublishedProductIDs: sortedProductIDs(dataset.Products, DesiredPublished),
		HiddenProductIDs:    sortedProductIDs(dataset.Products, DesiredHidden),
		ArchivedProductIDs:  sortedProductIDs(dataset.Products, DesiredArchived),
		Assets: []AssetExpectation{
			{Kind: "generated-local", Path: "assets/reference/reference-datasheet.pdf", Source: "generated by the reference-data command", Usage: "offline local PDF baseline"},
			{Kind: "external", Source: "https://docs.example.test/reference/", Usage: "non-routable synthetic external document references"},
			{Kind: "broken-negative", Source: "https://broken.invalid/reference.pdf", Usage: "isolated negative-link case only"},
		},
	}
	for _, product := range dataset.Products {
		manifest.ContentDistribution[product.ContentLevel]++
		for _, translation := range product.Translations {
			manifest.LocaleDistribution[translation.Locale]++
		}
	}
	manifest.Summary = ManifestSummary{
		BusinessTopCategories:     9,
		CategoriesIncludingSystem: len(dataset.Categories) + 2,
		SpecSets:                  len(dataset.SpecSets), Specs: len(dataset.Specs), Products: len(dataset.Products),
		Manufacturers: dictionaryCount(dataset, catalog.DictionaryManufacturer),
		Brands:        dictionaryCount(dataset, catalog.DictionaryBrand), Applications: dictionaryCount(dataset, catalog.DictionaryApplication),
		Published: len(manifest.PublishedProductIDs), Hidden: len(manifest.HiddenProductIDs), Archived: len(manifest.ArchivedProductIDs),
	}
	manifest.Taxonomy = taxonomyExpectations(dataset)
	manifest.CommonScopes = commonExpectations(dataset)
	queries := []struct{ name, query string }{
		{"exact-part", "abc123"}, {"case-distinct-part", "ABC123"}, {"literal-wildcards", "LITERAL%_REF"},
		{"unicode-casefold", "éco-sensor-ss"}, {"prefix", "REF-LDO"}, {"certain-zero", "NO-SUCH-PART-Ω-404"},
	}
	for _, query := range queries {
		ids := sortSearchResults(dataset.Products, query.query)
		manifest.Queries = append(manifest.Queries, QueryExpectation{Name: query.name, Query: query.query, Count: len(ids), ProductIDs: ids})
	}
	return manifest
}

func dictionaryCount(dataset Dataset, kind catalog.DictionaryKind) int {
	count := 0
	for _, entry := range dataset.Dictionaries {
		if entry.Kind == kind {
			count++
		}
	}
	return count
}

func taxonomyExpectations(dataset Dataset) []TaxonomyExpectation {
	byID := make(map[string]catalog.Category, len(dataset.Categories))
	for _, category := range dataset.Categories {
		byID[category.ID] = category
	}
	direct := make(map[string]int)
	for _, product := range dataset.Products {
		if product.DesiredState == DesiredPublished {
			direct[product.Product.CategoryID]++
		}
	}
	expectations := []TaxonomyExpectation{
		{ID: "cat_root", Path: "Root", DirectPublic: 0, SubtreePublic: len(sortedProductIDs(dataset.Products, DesiredPublished)) - direct[catalog.UncategorizedCategoryID]},
		{ID: catalog.UncategorizedCategoryID, ParentID: "cat_root", Path: "Root / Uncategorized", DirectPublic: direct[catalog.UncategorizedCategoryID], SubtreePublic: direct[catalog.UncategorizedCategoryID]},
	}
	for _, category := range dataset.Categories {
		subtree := direct[category.ID]
		for candidate := range byID {
			if candidate != category.ID && isDescendant(candidate, category.ID, byID) {
				subtree += direct[candidate]
			}
		}
		expectations = append(expectations, TaxonomyExpectation{
			ID: category.ID, ParentID: category.ParentID, Path: categoryPath(category.ID, byID), SpecSetID: dataset.CategorySpecSet[category.ID], DirectPublic: direct[category.ID], SubtreePublic: subtree,
		})
	}
	return expectations
}

func isDescendant(candidate, ancestor string, categories map[string]catalog.Category) bool {
	for candidate != "" && candidate != "cat_root" {
		category, ok := categories[candidate]
		if !ok {
			return false
		}
		if category.ParentID == ancestor {
			return true
		}
		candidate = category.ParentID
	}
	return false
}

func categoryPath(id string, categories map[string]catalog.Category) string {
	parts := []string{}
	for id != "" && id != "cat_root" {
		category, ok := categories[id]
		if !ok {
			break
		}
		parts = append(parts, category.Name)
		id = category.ParentID
	}
	slices.Reverse(parts)
	return "Root / " + strings.Join(parts, " / ")
}

func commonExpectations(dataset Dataset) []CommonExpectation {
	definitions := []struct {
		name       string
		categories []string
		specs      []string
	}{
		{"ldo-buck", []string{categoryID("semi-ldo"), categoryID("semi-buck")}, []string{"spc_input_voltage", "spc_output_voltage", "spc_output_current", "spc_package"}},
		{"ldo-buck-sensor", []string{categoryID("semi-ldo"), categoryID("semi-buck"), categoryID("sensor-temperature")}, []string{"spc_input_voltage", "spc_package"}},
		{"ldo-buck-sensor-connector", []string{categoryID("semi-ldo"), categoryID("semi-buck"), categoryID("sensor-temperature"), categoryID("connector-board")}, nil},
	}
	results := make([]CommonExpectation, 0, len(definitions))
	for _, definition := range definitions {
		categorySet := make(map[string]bool, len(definition.categories))
		for _, id := range definition.categories {
			categorySet[id] = true
		}
		var productIDs []string
		for _, product := range dataset.Products {
			if product.DesiredState == DesiredPublished && categorySet[product.Product.CategoryID] {
				productIDs = append(productIDs, product.Product.ID)
			}
		}
		slices.Sort(productIDs)
		results = append(results, CommonExpectation{Name: definition.name, CategoryIDs: definition.categories, ProductIDs: productIDs, SpecIDs: definition.specs})
	}
	return results
}
